<div>
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
    <script>
        var verifyCallback = function(response) {
            $('#submit').prop('disabled', false);
        };
        var onloadCallback = function() {
            grecaptcha.render('recaptcha', {
              'sitekey' : '6Le5kL8SAAAAACBclv8qe2MQR41a4Y1TKTaGBQFM',
              'callback' : verifyCallback,
              'theme' : 'dark'
            });
        };
        $(document).ready(function(){
            $('#submit').click(function(){
                var contactForm = $('#contact-form');
                $.ajax({
                    url: contactForm.attr('action'),
                    method: contactForm.attr('method'),
                    data: contactForm.serialize(),
                    success: function(html){
                        contactForm.parents('[html-include]').html(html);                        
                    }
                });
            });
            <?php if($this->successMessage || $this->errorMessage): ?>
                $('#alert-modal').modal('show');
            <?php endif;?>
        });
    </script>
    <form id="contact-form" action="<?php echo $this->contactForm->getAction(); ?>" method="<?php echo $this->contactForm->getMethod(); ?>">    
        <?php echo $this->contactForm->getElement('name'); ?>
        <?php echo $this->contactForm->getElement('email'); ?>
        <?php echo $this->contactForm->getElement('phone'); ?>
        <?php echo $this->contactForm->getElement('address'); ?>
        <?php echo $this->contactForm->getElement('comment'); ?>
        <div id="recaptcha" class="form-group"></div>
        <?php echo $this->contactForm->getElement('submit'); ?>
    </form>
    <div id="alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="mySmallModalLabel">Confirm</h4>
                </div>
                <div class="modal-body">
                    <?php if($this->successMessage): ?>
                        <div class="alert alert-success no-margin" role="alert"><?php echo $this->successMessage; ?></div>
                    <?php endif;?>
                    <?php if($this->errorMessage): ?>
                        <div class="alert alert-danger no-margin" role="alert"><?php echo $this->errorMessage; ?></div>
                    <?php endif;?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
</div>