<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            List of Post
            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'type'=> PAGE, 'language'=> 'vi')) ?>" class="btn btn-primary pull-right">
                <i class="fa fa-plus"></i> Add New Post
            </a>
        </h1>
    </div>
</div>
<!-- /.row -->

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>
                Category
            </th>
            <th>
                Thumbnail
            </th>
            <th>
                Title
            </th>
            <th>
                Created date
            </th>
            <th>
                Creator
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->paginator as $key => $value):?>
            <tr>
                <td>
                    <?php echo $value['display_name'];?>
                </td>
                <td>
                    <img src="<?php echo $value['thumbnail'];?>" clas="img-responsive" style="max-width: 100px;"/>
                </td>
                <td>
                    <?php echo $value['title'];?>
                </td>
                <td>
                    <?php echo $value['created_date'];?>
                </td>
                <td>
                    <?php echo $value['name'];?>
                </td>
                <td>
                    <?php if($key > 0):?>
                        <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'swap', 'post_id' => $value['id'], 'order_id' => $value['order_id'], 'above_post_id' => $this->paginator->getItem($key)['id'], 'above_order_id' => $this->paginator->getItem($key)['order_id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Up">
                            <i class="fa fa-arrow-up"></i>
                        </a>
                    <?php endif;?>
                    
                    <?php if($key < $this->paginator->getCurrentItemCount() - 1):?>
                        <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'swap', 'post_id' => $value['id'], 'order_id' => $value['order_id'], 'above_post_id' => $this->paginator->getItem($key+2)['id'], 'above_order_id' => $this->paginator->getItem($key+2)['order_id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Down">
                            <i class="fa fa-arrow-down"></i>
                        </a>
                    <?php endif;?>
                    
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Sửa">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'delete', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Xóa" need-confirm>
                        <i class="fa fa-times"></i>
                    </a>
                </td>
                <?php $oldvalue = $value;?>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml');?>
<div class="clearfix"></div>