<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:READONLY']) || isset($this->layout()->admin_role['SIDEBAR:ADD']) || isset($this->layout()->admin_role['SIDEBAR:EDIT']) || isset($this->layout()->admin_role['SIDEBAR:DELETE'])): ?>

    <form action="<?php echo $this->sidebarForm->getAction(); ?>" method="<?php echo $this->sidebarForm->getMethod(); ?>">
        <?php if(isset($this->layout()->admin_role['SIDEBAR:READONLY'])): ?>
            <?php echo $this->render('form-disable.phtml');?>
        <?php endif;?>
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <header>
                        <div class="icons">
                            <i class="fa fa-pencil"></i>
                        </div>
                        <h5></h5>
                        <div class="toolbar">
                            <div class="btn-group">
                                <?php echo $this->sidebarForm->getElement('submit'); ?>
                            </div>
                        </div>
                    </header>
                    <div class="body">
                        <div class="sidebar-form">
                            <?php if($this->errorMessage != ""): ?>
                            <p class="error">
                                <?php echo $this->errorMessage; ?></p>
                            <?php endif; ?>

                            <?php echo $this->sidebarForm->getElement('id'); ?>
                            <?php echo $this->sidebarForm->getElement('name'); ?>
                            <?php echo $this->sidebarForm->getElement('post_id'); ?>
                            <?php echo $this->sidebarForm->getElement('title'); ?>
                            <?php echo $this->sidebarForm->getElement('content'); ?>
                            <?php echo $this->sidebarForm->getElement('has_title'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>