<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:READONLY']) || isset($this->layout()->admin_role['SIDEBAR:ADD']) || isset($this->layout()->admin_role['SIDEBAR:EDIT']) || isset($this->layout()->admin_role['SIDEBAR:DELETE'])): ?>
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:ADD'])): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'sidebar', 'action'=> 'detail')) ?>">
                                    <i class="fa fa-plus"></i> Add Sidebar
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <div class="nestable-list" url="/admin/configuration/order" level="1">
                        <ol class="dd-list">                            
                            <?php foreach($this->sidebar as $key => $value):?>
                                <li class="dd-item" data-id="<?php echo $value['sidebar']['id'];?>">
                                    <div class="dd-handle">
                                        <div class="col-sm-3">
                                            <?php echo $value['post']['title'];?>
                                        </div>
                                        <?php if(isset($this->layout()->admin_role['SIDEBAR:READONLY'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'sidebar', 'action'=> 'detail', 'id' => $value['sidebar']['id'] )) ?>">
                                                <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="View"></i>
                                            </a>
                                        <?php endif;?>

                                        <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:DELETE'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'sidebar', 'action'=> 'delete', 'id' => $value['sidebar']['id'] , 'post_id' => $value['post']['id'])) ?>" need-confirm>
                                                <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                            </a>
                                        <?php endif;?>
                                        
                                        <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:EDIT'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'sidebar', 'action'=> 'detail', 'id' => $value['sidebar']['id'] )) ?>">
                                                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                            </a>
                                        <?php endif;?>

                                        
                                        <div class="clearfix"></div>
                                    </div>
                                </li>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>