<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Slide <small>Add/Edit slide item</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Slide
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<div class="slide-form">
    <?php if($this->errorMessage != ""): ?>
    <p class="error">
        <?php echo $this->errorMessage; ?></p>
    <?php endif; ?>

    <form enctype="multipart/form-data" action="<?php echo $this->slideForm->getAction(); ?>" method="<?php echo $this->slideForm->getMethod(); ?>">            
        <?php echo $this->slideForm->getElement('id'); ?>
        <?php echo $this->slideForm->getElement('name'); ?>
        <?php echo $this->slideForm->getElement('value'); ?>
        <?php echo $this->slideForm->getElement('file'); ?>
        <img class="img-responsive" src="<?php echo $this->slideForm->getElement('value')->getValue(); ?>">
        <?php echo $this->slideForm->getElement('post_id'); ?>        

        <?php echo $this->slideForm->getElement('submit'); ?>
    </form>
</div>