<?php if ($this->pageCount): ?>
<nav>
    <ul class="pagination">
        <li class="<?php echo isset($this->previous)?'':'disabled' ?>">
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                <span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span>
            </a>
        </li>
        
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page == $this->current): ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?> <span class="sr-only">(current)</span></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <li class="<?php echo isset($this->next)?'':'disabled' ?>">
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
                <span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>
<?php else:?>
    No data available
<?php endif; ?>