<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()?>
    <?php echo $this->headScript()?>
</head>

<body class="admin-page <?php echo $this->layout()->mainClassesOfPage ?>" style="overflow: hidden;">
    <?php if ($this->layout()->inIframe): ?>
        <?php echo $this->layout()->content ?>
    <?php elseif ($this->layout()->admin_username): ?>
        <div class="bg-dark dk" id="wrap">
            <div id="top">
                <!-- .navbar -->
                <nav class="navbar navbar-inverse navbar-static-top">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <header class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span> 
                            <span class="icon-bar"></span> 
                            <span class="icon-bar"></span> 
                            <span class="icon-bar"></span> 
                            </button>
                            <a href="index.html" class="navbar-brand">
                                Bappro Admin Panel
                            </a> 
                        </header>
                        <div class="topnav">
                            <div class="btn-group">
                                <a data-placement="bottom" class="btn btn-default btn-sm" id="toggleFullScreen">
                                    <i class="glyphicon glyphicon-fullscreen"></i>
                                </a> 
                            </div>
                            <div class="btn-group">
                                <a data-placement="bottom" class="btn btn-default btn-sm">
                                    <i class="fa fa-envelope"></i>
                                    <span class="label label-warning">0</span> 
                                </a> 
                                <a data-placement="bottom" href="#" class="btn btn-default btn-sm">
                                    <i class="fa fa-comments"></i>
                                    <span class="label label-danger">0</span> 
                                </a> 
                                <a data-toggle="modal" class="btn btn-default btn-sm" href="#help-modal">
                                    <i class="fa fa-question"></i>
                                </a> 
                            </div>
                            <div class="btn-group">                        
                                <a href="/admin/login/logout" class="btn btn-metis-1 btn-sm">
                                    <i class="fa fa-power-off"></i>
                                </a> 
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm toggle-left" id="menu-toggle">
                                    <i class="fa fa-bars"></i>
                                </a>                                 
                            </div>
                        </div>
                    </div>
                    <!-- /.container-fluid -->
                </nav>
                <!-- /.navbar -->
                <!--<header class="head">
                    <div class="search-bar">
                        <form class="main-search" action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Live Search ...">
                                <span class="input-group-btn">
                                <button class="btn btn-primary btn-sm text-muted" type="button">
                                <i class="fa fa-search"></i>
                                </button>
                                </span> 
                            </div>
                        </form>
                    </div>
                    <div class="main-bar">
                        <h3>
                            <i class="fa fa-<?php echo $this->layout()->icon; ?>"></i>&nbsp; <?php echo $this->layout()->title; ?>
                        </h3>
                    </div>
                </header>-->
                <!-- /.head -->
            </div>
            <!-- /#top -->
            <div id="left" style="overflow-x: auto;">
                <div class="media user-media bg-dark dker">
                    <div class="user-media-toggleHover">
                        <span class="fa fa-user"></span> 
                    </div>
                    <div class="user-wrapper bg-dark">
                        <a class="user-link" href="">
                        <img class="media-object img-thumbnail user-img" alt="User Picture" src="/public/images/admin-icon.png">
                        <span class="label label-danger user-label">0</span> 
                        </a> 
                        <div class="media-body">
                            <h5 class="media-heading"><?php echo $this->layout()->admin_name; ?></h5>
                            <ul class="list-unstyled user-info">
                                <li> 
                                    <a href="#">Administrator</a>
                                </li>
                                <li>Last Access :
                                    <br>
                                    <small>
                                    <i class="fa fa-calendar"></i>&nbsp;16 Mar 16:32</small> 
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- #menu -->
                <ul id="menu" class="bg-blue dker">
                    <li class="nav-header">Menu</li>
                    <li class="nav-divider"></li>
                    <li class="">
                        <a href="/admin/dashboard">
                            <i class="fa fa-dashboard"></i><span class="link-title">&nbsp;Dashboard</span> 
                        </a> 
                    </li>

                    <li>
                        <a href="javascript:void(0);">
                            <i class="fa fa-fw fa-file-text"></i>
                            <span class="link-title">Post</span> 
                            <span class="fa arrow"></span> 
                        </a>
                        <ul>
                            <!--<?php if($this->layout()->admin_issuper): ?>
                            <li>
                                <a href="/admin/post/index">
                                    <i class="fa fa-angle-right"></i>&nbsp; All
                                </a>
                            </li>
                            <?php endif;?>-->

                            <?php foreach($this->layout()->allCategory as $category):?>
                                <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role[$category['name'].':READONLY']) || isset($this->layout()->admin_role[$category['name'].':ADD']) || isset($this->layout()->admin_role[$category['name'].':EDIT']) || isset($this->layout()->admin_role[$category['name'].':DELETE'])): ?>
                                <li>
                                    <a href="/admin/post/index/category/<?php echo $category['name'] ?>">
                                        <i class="fa fa-angle-right"></i>&nbsp; <?php echo $category[ 'display_name']?>
                                    </a>
                                </li>
                                <?php endif;?>
                            <?php endforeach;?>

                            <!--<?php if($this->layout()->admin_issuper): ?>
                            <li>
                                <a href="/admin/post/detail">
                                    <i class="fa fa-angle-right"></i>&nbsp; Add Post
                                </a>
                            </li>
                            <?php endif;?>-->
                        </ul>
                    </li>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['MENU:READONLY']) || isset($this->layout()->admin_role['MENU:ADD']) || isset($this->layout()->admin_role['MENU:EDIT']) || isset($this->layout()->admin_role['MENU:DELETE'])): ?>
                    <li>
                        <a href="javascript:void(0);">
                            <i class="fa fa-fw fa-sitemap"></i>
                            <span class="link-title">Menu</span> 
                            <span class="fa arrow"></span>
                        </a>
                        <ul>
                            <?php foreach($this->layout()->menu as $key => $menu):?>
                            <li>
                                <a href="/admin/menu/index/name/<?php echo $key ?>">
                                    <i class="fa fa-angle-right"></i>&nbsp; <?php echo ucfirst(strtolower(str_replace('CONF', ' ', str_replace('_', ' ', $key)))) ?>
                                </a>
                            </li>
                            <?php endforeach;?>
                            <?php if($this->layout()->admin_issuper): ?>
                            <li>
                                <a href="/admin/menu/add">
                                    <i class="fa fa-plus"></i> Add menu
                                </a>
                            </li>
                            <?php endif;?>
                        </ul>
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SLIDE:READONLY']) || isset($this->layout()->admin_role['SLIDE:ADD']) || isset($this->layout()->admin_role['SLIDE:EDIT']) || isset($this->layout()->admin_role['SLIDE:DELETE'])): ?>
                    <li>
                        <a href="javascript:void(0);">
                            <i class="fa fa-fw fa-indent"></i>
                            <span class="link-title">Slide</span> 
                            <span class="fa arrow"></span>
                        </a>
                        <ul>
                            <?php foreach($this->layout()->slide as $key => $slide):?>
                            <li>
                                <a href="/admin/slide/index/name/<?php echo $key ?>">
                                    <i class="fa fa-angle-right"></i>&nbsp; <?php echo ucfirst(strtolower(str_replace('CONF', ' ', str_replace('_', ' ', $key)))) ?>
                                </a>
                            </li>
                            <?php endforeach;?>
                            <?php if($this->layout()->admin_issuper): ?>
                            <li>
                                <a href="/admin/slide/add">
                                    <i class="fa fa-plus"></i> Add slide
                                </a>
                            </li>
                            <?php endif;?>
                        </ul>
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SIDEBAR:READONLY']) || isset($this->layout()->admin_role['SIDEBAR:ADD']) || isset($this->layout()->admin_role['SIDEBAR:EDIT']) || isset($this->layout()->admin_role['SIDEBAR:DELETE'])): ?>
                    <li>
                        <a href="javascript:void(0);">
                            <i class="fa fa-fw fa-th-list"></i> 
                            <span class="link-title">Sidebar</span> 
                            <span class="fa arrow"></span>
                        </a>
                        <ul id="sidebar" class="collapse">
                            <?php foreach($this->layout()->sidebar as $key => $sidebar):?>
                            <li>
                                <a href="/admin/sidebar/index/name/<?php echo $key ?>">
                                    <i class="fa fa-angle-right"></i>&nbsp; <?php echo ucfirst(strtolower(str_replace('CONF', ' ', str_replace('_', ' ', $key)))) ?>
                                </a>
                            </li>
                            <?php endforeach;?>
                            <?php if($this->layout()->admin_issuper): ?>
                            <li>
                                <a href="/admin/sidebar/add">
                                    <i class="fa fa-plus"></i> Add sidebar
                                </a>
                            </li>
                            <?php endif;?>
                        </ul>
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['MEDIA:READONLY']) || isset($this->layout()->admin_role['MEDIA:ADD']) || isset($this->layout()->admin_role['MEDIA:EDIT']) || isset($this->layout()->admin_role['MEDIA:DELETE'])): ?>
                    <li>
                        <a href="/admin/media/index">
                            <i class="fa fa-fw fa-picture-o"></i>
                            <span class="link-title">Media</span>
                        </a>
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:READONLY']) || isset($this->layout()->admin_role['CATEGORY:ADD']) || isset($this->layout()->admin_role['CATEGORY:EDIT']) || isset($this->layout()->admin_role['CATEGORY:DELETE'])): ?>
                    <li>
                        <a href="/admin/category/index">
                            <i class="fa fa-fw fa-list-ol"></i>
                            <span class="link-title">Post category</span>
                        </a>                            
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CONFIGURATION:READONLY']) || isset($this->layout()->admin_role['CONFIGURATION:ADD']) || isset($this->layout()->admin_role['CONFIGURATION:EDIT']) || isset($this->layout()->admin_role['CONFIGURATION:DELETE'])): ?>
                    <li>
                        <a href="/admin/configuration/index">
                            <i class="fa fa-fw fa-cog"></i>
                            <span class="link-title">Configuration</span>
                        </a>                            
                    </li>
                    <?php endif;?>

                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['USER:READONLY']) || isset($this->layout()->admin_role['USER:ADD']) || isset($this->layout()->admin_role['USER:EDIT']) || isset($this->layout()->admin_role['USER:DELETE'])): ?>
                    <li>
                        <a href="/admin/user/index">
                            <i class="fa fa-fw fa-users"></i>
                            <span class="link-title">User</span>
                        </a>                            
                    </li> 
                    <?php endif;?>                
                </ul>
                <!-- /#menu -->
            </div>
            <!-- /#left -->
            <div id="content-container">
                <div class="outer">
                    <div class="inner bg-light lter">
                        <iframe id="content-iframe" width="100%" style="border: none;">
                        </iframe>                        
                    </div>
                    <!-- /.inner -->
                </div>
                <!-- /.outer -->
            </div>            
        </div>
        <!-- /#wrap -->    
    <?php else: ?>
        <?php echo $this->layout()->content ?>
    <?php endif; ?>
    
    <div id="confirm-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="mySmallModalLabel">Confirm</h4>
                </div>
                <div class="modal-body">
                    Are you sure?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-danger" id="yes-button">Yes</button>
                </div>
            </div>
        </div>
    </div>
    
    <div id="help-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">About</h4>
                </div>
                <div class="modal-body">
                    Bappro Admin Tool v0.2.0
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Yes</button>
                </div>
            </div>
        </div>
    </div>
</body>

</html>