<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->layout()->configurations[META_HEADER_CONF]['value'] ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()?>
    <?php echo $this->headScript()?>
</head>

<body class="main-page <?php echo $this->layout()->mainClassesOfPage ?>">
    <header>
        <div class="banner">
            <div class="container">
                <div class="col-xs-4 col-sm-3 no-padding">
                    <img src="<?php echo $this->layout()->configurations[LOGO_IMG_CONF]['value'] ?>" class="logo img-responsive">                    
                </div>
                <div class="col-xs-8 col-sm-offset-0 col-sm-4 no-padding">
                    <img src="<?php echo $this->layout()->configurations[LOGO_IMG_2_CONF]['value'] ?>" class="img-responsive">                    
                </div>
                <div class="col-xs-12 col-sm-4 no-padding pull-right">
                    <div class="input-group search-control">
                        <input id="search-text" type="text" class="form-control" placeholder="search">
                        <span id="search-button" class="input-group-addon">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>                    
                </div>
            </div>
        </div>
        <hr class="divider">
        <div class="header-menu" data-spy="affix" data-offset-top="155" data-offset-bottom="10">
            <div class="container">
                <div class="row">
                    <div class="navbar navbar-default no-border no-background">                        
                        <div class="navbar-header">
                            <a type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                        </div>
                        <div class="collapse navbar-collapse navbar-ex1-collapse">
                            <ul class="nav navbar-nav">
                                <?php foreach($this->layout()->menu[HEADER_MENU_CONF] as $menu):?>                                
                                    <?php if(count($menu['submenu']) > 0): ?>
                                        <li class="dropdown" role="presentation">
                                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($menu['post']) ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                                <?php echo $menu['post'][ 'title'] ?> <span class="caret"></span>
                                            </a>
                                            <ul class="dropdown-menu" role="menu">
                                                <?php foreach($menu['submenu'] as $submenu):?>
                                                    <li role="presentation">
                                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($submenu['post']) ?>">
                                                            <?php echo mb_strtolower($submenu['post'][ 'title'], 'utf8') ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach;?>
                                            </ul>
                                        </li>
                                    <?php else:?>
                                        <li role="presentation">
                                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($menu['post']) ?>">
                                                <?php echo $menu['post']['title'] ?>
                                            </a>
                                        </li>
                                    <?php endif;?>                                
                                <?php endforeach;?>
                            </ul>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </header>
    <?php if($this->layout()->hasSlide):?>
    <section id="main-slide">
        <div class="container">
            <div class="row">                
                <div class="col-sm-9 pull-right slide">
                    <div class="carousel" data-ride="carousel">
                        <div class="carousel-inner">
                            <?php foreach($this->layout()->slide[MAIN_SLIDE_CONF] as $key => $slide):?>
                                <div class="item <?php echo $key==0?'active':'' ?>">
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($slide['post']) ?>">
                                        <img src="<?php echo $slide['slide']['value'] ?>" class="center-block img-responsive">
                                    </a>
                                </div>
                            <?php endforeach;?>
                        </div>
                        <ol class="carousel-indicators">
                            <?php foreach($this->layout()->slide[MAIN_SLIDE_CONF] as $key => $slide):?>
                                <li data-target="#main-slide .carousel" data-slide-to="<?php echo $key?>" class="<?php echo $key==0?'active':'' ?>"></li>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </div>
                <div class="col-sm-3 slidesidebar">
                    <?php echo $this->layout()->sidebar[RIGHT_SIDEBAR_CONF][0]['post']['content'] ?>
                </div>
            </div>
        </div>
    </section>
    <?php endif;?>
    <?php if($this->layout()->hasTopSidebar):?>
    <section id="top-sidebar">
        <div class="container">
            <div class="row">
                <?php foreach($this->layout()->sidebar[TOP_SIDEBAR_CONF] as $i => $sidebar):?>
                    <?php if($i % 3 == 2):?>
                        <div class="col-sm-6 top-sidebar">                        
                            <?php echo $sidebar['post']['content'] ?>                            
                        </div>                    
                    <?php else:?>
                        <div class="col-sm-3 top-sidebar">
                            <?php echo $sidebar['post']['content'] ?>
                        </div>
                    <?php endif;?>
                <?php endforeach;?>
            </div>
        </div>
    </section>
    <?php endif;?>
    <section id="main-content">
        <div class="container">
            <div class="row">
                <div class="pull-right <?php echo $this->layout()->hasRightSidebar?'col-sm-9':'col-sm-12' ?>">
                    <?php echo $this->layout()->content ?>
                </div>
                <div class="clearfix visible-xs"></div>
                <?php if($this->layout()->hasRightSidebar):?>
                    <div class="col-sm-3">
                        <div class="row">
                            <?php foreach($this->layout()->sidebar[RIGHT_SIDEBAR_CONF] as $i => $sidebar):?>
                                <?php if($i != 0):?>
                                    <div class="col-sm-12">
                                        <div class="right-sidebar panel panel-danger">
                                            <?php if($sidebar['post']['has_title']):?>
                                                <div class="panel-heading">
                                                    <?php echo $sidebar['post']['title'] ?>
                                                </div>
                                            <?php endif;?>
                                            <div class="panel-body">
                                                <?php echo $sidebar['post']['content'] ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif;?>
                            <?php endforeach;?>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </section>
    <footer>
        <div class="container">
            <div class="footer-background col-md-12">
                <div class="row">
                    <?php echo $this->layout()->configurations[FOOTER_INFO_CONF]['value'] ?>
                </div>
            </div>
        </div>        
    </footer>
    
    <?php echo $this->layout()->configurations[PLUGIN_FOR_ALL_PAGE_CONF]['value'] ?>
    
</body>

</html>
