<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:READONLY']) || isset($this->layout()->admin_role['CATEGORY:ADD']) || isset($this->layout()->admin_role['CATEGORY:EDIT']) || isset($this->layout()->admin_role['CATEGORY:DELETE'])): ?>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:ADD'])): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail')) ?>">
                                    <i class="fa fa-plus"></i> Add Category
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <table class="table table-bordered table-condensed table-hover table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Display name
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->category as $key => $value):?>
                                <tr>
                                    <td>
                                        <?php echo $value['name'];?>
                                    </td>
                                    <td>
                                        <?php echo $value['displayName'];?>
                                    </td>
                                    <td class="text-right">
                                        <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:ADD'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'link_id' => $value['id'] )) ?>">
                                                <i class="fa fa-plus" data-toggle="tooltip" data-placement="top" title="Add Child"></i>
                                            </a>
                                        <?php endif;?>
                                        
                                        <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:EDIT'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value['id'] )) ?>">
                                                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                            </a>
                                        <?php endif;?>

                                        <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:DELETE'])): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'delete', 'id' => $value['id'] )) ?>" need-confirm>
                                                <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete" ></i>
                                            </a>
                                        <?php endif;?>
                                    </td>
                                </tr>
                                <?php foreach($value['subCategory'] as $value1):?>
                                    <tr>
                                        <td>
                                            -------<?php echo $value1['name'];?>
                                        </td>
                                        <td>
                                            <?php echo $value1['displayName'];?>
                                        </td>
                                        <td class="text-right">
                                            <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:EDIT'])): ?>
                                                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value1['id'] )) ?>">
                                                    <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                                </a>
                                            <?php endif;?>

                                            <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY:DELETE'])): ?>
                                                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'delete', 'id' => $value1['id'] )) ?>" need-confirm>
                                                    <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                                </a>
                                            <?php endif;?>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>