<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role[$this->category.':READONLY']) || isset($this->layout()->admin_role[$this->category.':ADD']) || isset($this->layout()->admin_role[$this->category.':EDIT']) || isset($this->layout()->admin_role[$this->category.':DELETE'])): ?>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role[$this->category.':ADD'])): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'type'=> PAGE, 'language'=> 'vi')) ?>">
                                    <i class="fa fa-plus"></i> Add New Post
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <table class="table table-bordered table-condensed table-hover table-striped data-table">
                        <thead>
                            <tr>
                                <th aria-sort="descending">
                                    Order
                                </th>
                                <th>
                                    Category
                                </th>
                                <th>
                                    Thumbnail
                                </th>
                                <th>
                                    Title
                                </th>
                                <th>
                                    Category to líst
                                </th>
                                <th>
                                    Created date
                                </th>
                                <th>
                                    Creator
                                </th>                                
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->paginator as $key => $value):?>
                            <tr>
                                <td>
                                    <?php echo $value[ 'order_id'];?>
                                </td>
                                <td>
                                    <?php foreach($this->layout()->allCategory as $ca):?>
                                        <?php if(strpos($value[ 'category'], ','.$ca[ 'name']. ',')> -1):?> |
                                            <?php echo $ca[ 'display_name'];?> |
                                            <br>
                                        <?php endif;?>
                                    <?php endforeach;?>
                                </td>
                                <td>
                                    <img src="<?php echo $value['thumbnail'];?>" clas="img-responsive" style="max-width: 100px;" />
                                </td>
                                <td>
                                    <?php echo $value[ 'title'];?>
                                </td>
                                <td>
                                    <?php foreach($this->layout()->allCategory as $ca):?>
                                        <?php if(strpos($value[ 'category_to_list'], ','.$ca[ 'name']. ',')> -1):?> |
                                            <?php echo $ca[ 'display_name'];?> |
                                            <br>
                                        <?php endif;?>
                                    <?php endforeach;?>
                                </td>
                                <td>
                                    <?php echo $value[ 'created_date'];?>
                                </td>
                                <td>
                                    <?php echo $value[ 'name'];?>
                                </td>
                                <td class="text-right">
                                    <?php if(isset($this->layout()->admin_role[$this->category.':READONLY'])): ?>
                                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'id' => $value['id'] )) ?>">
                                        <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="View"></i>
                                    </a>
                                    <?php endif;?>

                                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role[$this->category.':EDIT'])): ?>
                                        <?php if($key> 0):?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'swap', 'post_id' => $value['id'], 'order_id' => $value['order_id'], 'above_post_id' => $this->paginator->getItem($key)['id'], 'above_order_id' => $this->paginator->getItem($key)['order_id'] )) ?>">
                                                <i class="fa fa-arrow-up" data-toggle="tooltip" data-placement="top" title="Up"></i>
                                            </a>
                                        <?php endif;?>

                                        <?php if($key < $this->paginator->getCurrentItemCount() - 1):?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'swap', 'post_id' => $value['id'], 'order_id' => $value['order_id'], 'above_post_id' => $this->paginator->getItem($key+2)['id'], 'above_order_id' => $this->paginator->getItem($key+2)['order_id'] )) ?>">
                                                <i class="fa fa-arrow-down" data-toggle="tooltip" data-placement="top" title="Down"></i>
                                            </a>
                                        <?php endif;?>

                                        <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'id' => $value['id'] )) ?>">
                                            <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                        </a>
                                    <?php endif;?>

                                    <?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role[$this->category.':DELETE'])): ?>
                                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'delete', 'id' => $value['id'] )) ?>" need-confirm>
                                        <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                    </a>
                                    <?php endif;?>
                                </td>
                                <?php $oldvalue = $value;?>
                            </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>