<style>
    .post-container {
        margin-top: 20px;
        position: relative;
    }
    
    .post-media {
        width: 100%;
        border-style: solid;
        border-width: 2px;
        border-color: #3c663d;
    }
    
    .post-content {
        float: right;
        width: 570px;        
        margin-top: 20px;
        font-size: 18px;
    }
    
    .post-map {
        width: 100%;
        margin-top: 20px;
    }
    
    .post-title {
        font-size: 24px;
        color: #ffffff;
        position: absolute;
        top: 240px;
        text-transform: uppercase;
        background-color: #3c663d;
        padding: 5px 45px;
    }
    
    .post-like-share {
        margin-top: 10px;
    }
    
    .contact-form {
        float: right;
        width: 570px;
        margin-top: 20px;
        margin-left: 30px;
    }
    
    .contact-form input,
    .contact-form textarea {
        background-color: #3c663d;
        color: #ffffff;
        width: 100%;
        margin-bottom: 10px;
    }
    
    .contact-form button {
        background-color: #3c663d;
        color: #ffffff;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {
        .post-title {
            top: 195px;
        }
        .post-content {
            width: 470px;
        }
        .contact-form {
            width: 470px;
        }
    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .post-title {
            top: 150px;
            font-size: 20px;
        }
        .post-content {
            width: 360px;
        }
        .contact-form {
            width: 360px;
        }
    }
    
    @media (max-width: 767px) {
        .post-content {
            width: 100%;
        }
        .contact-form {
            width: 100%;
        }
    }
</style>
<div class="post-container">

    <?php if($this->post['has_media']): ?>
    <div class="carousel post-media hidden-xs" data-ride="carousel">
        <div class="carousel-inner">
            <?php $ms=explode( ';', preg_replace( '/;+/', ';', trim($this->post['media'], ';'))); ?>
            <?php foreach($ms as $key=> $media):?>
            <div class="item <?php echo $key==0?'active':'' ?>">
                <img src="<?php echo $media ?>" class="center-block img-responsive">
            </div>
            <?php endforeach;?>
        </div>
    </div>
    <?php endif;?>

    <?php if($this->post['has_title']): ?>
    <div class="post-title hidden-xs">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title');?>
    </div>
    <?php endif;?>

    <?php if($this->post['has_description']): ?>
    <div class="post-description">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'description');?>
    </div>
    <?php endif;?>

    <?php if($this->post['has_like_share']): ?>
    <div class="post-like-share">
        <div class="fb-like" data-href="<?php echo $this->fullUrl; ?>" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
    </div>
    <?php endif;?>

    <script>
        function sendContact(){
            if($('#name').val() != '' && $('#email').val() != '' && $('#comment').val() != ''){
                $.ajax({
                    url: '/mail/send-contact',
                    data: $('#contact-form').serializeArray(),
                    method: 'POST',
                    success: function(){
                        alert('Cảm ơn bạn đã đóng góp ý kiến cho chúng tôi!');
                        window.location.href = '/';
                    }
                });        
            }else{
                alert('Vui lòng nhập đủ thông tin!');
            }
        }
    </script>
    <div class="contact-form">
        <form id="contact-form">
            <input id="name" name="name" type="text" class="form-control" placeholder="Họ và tên">
            <input id="email" name="email" type="text" class="form-control" placeholder="Email">
            <textarea id="comment" name="comment" class="form-control" rows="5" placeholder="Nội dung"></textarea>
            <button type="button" class="btn btn-default pull-right" onclick="sendContact()">Gửi</button>
        </form>
    </div>
    
    <?php if($this->post['has_content']): ?>
        <?php echo $this->post['content'] ?>        
    <?php endif;?>

    <?php if($this->post['has_advertisment']): ?>
    <div class="post-advertisment">
        <?php echo $this->layout()->configurations[POST_ADVERTISMENT_CONF]['value'] ?>
    </div>
    <?php endif;?>

    <?php if($this->post['has_comment']): ?>
    <div class="comment">
        <div class="fb-comments" data-href="<?php echo $this->fullUrl; ?>" data-width="100%" data-num-posts="10"></div>
    </div>
    <?php endif;?>
</div>