<div>
    <?php if($this->post['has_breadcrumb']): ?>
        <ol class="breadcrumb">
            <?php foreach($this->breadcrumb as $item):?>
                <li>
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($item) ?>"><?php echo Utils_StringUtils::getTextFromPost($item, 'title'); ?></a>
                </li>
            <?php endforeach;?>
        </ol>
    <?php endif;?>


    <?php if($this->post['has_title']): ?>
        <!--<h3 class="title-post">
            <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title'); ?>
        </h3>-->
        <div class="panel panel-primary mb-10 no-border">
            <div class="panel-heading">
                <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title'); ?>
            </div>
        </div>
    <?php endif;?>


    <?php if($this->post['has_description']): ?>
        <div class="description-post row">
            <div class="col-sm-6">
                <div id="preview-post" class="carousel media-post" data-ride="carousel">
                    <div class="carousel-inner">                    
                        <?php $ms = explode(';', preg_replace('/;+/', ';', trim($this->post['media'], ';'))); ?>
                        <?php foreach($ms as $key => $media):?>
                            <div class="item <?php echo $key==0?'active':'' ?>">
                                <img src="<?php echo $media ?>" class="center-block img-responsive">
                            </div>
                        <?php endforeach;?>
                    </div>                
                    <a class="left carousel-control" href="#preview-post" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#preview-post" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <ol class="carousel-indicators">
                    <?php foreach($ms as $key => $media):?>
                        <li data-target="#preview-post" href="#preview-post" data-slide-to="<?php echo $key?>">
                            <img src="<?php echo $media ?>" class="center-block img-responsive">
                        </li>
                    <?php endforeach;?>
                </ol>
            </div>
            <div class="col-sm-6">
                <div class="panel panel-primary mb-10 no-border">
                    <div class="panel-heading">
                        Mô tả
                    </div>
                </div>
                <p>
                    <?php echo $this->post['description'];?>
                </p>
                <h4 class="old-price"><?php echo $this->post['old_price'];?></h4>
                <div class="clearfix"></div>
                <h4 class="price"><?php echo $this->post['price'];?></h4>
            </div>
        </div>
        <div class="clearfix"></div>

        <?php if($this->post['has_like_share']): ?>
            <div class="like-share-post">
                <div class="fb-like" data-href="<?php echo $this->fullUrl; ?>" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
            </div>        
        <?php endif;?>

        <div class="panel panel-primary no-margin no-border">
            <div class="panel-heading">
                Chi tiết
            </div>
        </div>
    <?php endif;?>


    <?php if($this->post['has_content']): ?>
        <div class="content-post">
            <?php echo $this->post['content'] ?>
        </div>
    <?php endif;?>


    <?php if($this->post['is_front_page']): ?>
        <div class="front-page-content">
            <?php foreach($this->posts as $value):?>
                <?php if(isset($value['is_filter_page']) && $value['is_filter_page'] && $value['category'] == 'GIOI_THIEU'): ?>
                    <div class="gt-container">
                        <div class="fg-title">
                            <div class="fg-title-text">
                                <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                            </div>
                            <div class="fg-title-line">
                                <div></div>
                            </div>
                        </div>
                        <div class="gt-content">
                            <?php foreach($value['subPost'] as $index => $subValue):?>
                                <?php if($index == 0): ?>
                                    <div class="gt-content-1">
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-thumbnail-1">
                                                <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                            </div>
                                        </a>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-title-1">
                                                <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                            </div>
                                        </a>
                                        <div class="gt-description-1">
                                            <?php echo Utils_StringUtils::getTextFromPost($subValue, 'description');?>
                                        </div>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-more-1">
                                                Xem thêm
                                            </div>
                                        </a>
                                        <div class="clearfix"></div>
                                    </div>
                                    
                                <?php elseif($index < 4): ?>
                                    <div class="gt-content-2">
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-title-2">
                                                <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                            </div>
                                        </a>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-thumbnail-2">
                                                <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                            </div>
                                        </a>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-more-2">
                                                Xem
                                            </div>
                                        </a>
                                    </div>
                                <?php endif;?>
                            <?php endforeach;?>
                            <div class="clearfix"></div>
                        </div>
                        <div class="gt-sidebar">
                            <div class="gt-sidebar-1">
                                <div class="gt-title-1">
                                    <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                                </div>
                                <div class="gt-title-re-1">
                                </div>
                                <div class="gt-list">
                                    <?php foreach($value['subPost'] as $index => $subValue):?>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="gt-list-item">
                                                <?php if($index == 0): ?>
                                                    Tổng Quan
                                                <?php else: ?>
                                                    <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                                <?php endif;?>                                            
                                            </div>
                                        </a>
                                    <?php endforeach;?>
                                </div>
                            </div>
                            <div class="gt-sidebar-1">
                                <div class="gt-title-1">
                                    Tài chính & thời tiết
                                </div>
                                <div class="gt-title-re-1">
                                </div>
                                <div>
                                    <span style="display: block !important; width: 180px; text-align: center; font-family: sans-serif; font-size: 12px;"><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:94114.1.99999&bannertypeclick=wu_travel_map1" title="San Francisco, California Weather Forecast" target="_blank"><img src="http://weathersticker.wunderground.com/weathersticker/cgi-bin/banner/ban/wxBanner?bannertype=wu_travel_map1_metric&airportcode=KSFO&ForcedCity=San Francisco&ForcedState=CA&zip=94114&language=EN" alt="Find more about Weather in San Francisco, CA" width="160" /></a><br><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:94114.1.99999&bannertypeclick=wu_travel_map1" title="Get latest Weather Forecast updates" style="font-family: sans-serif; font-size: 12px" target="_blank">Click for weather forecast</a></span>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                <?php endif;?>
            
                <?php if(isset($value['is_filter_page']) && $value['is_filter_page'] && $value['category'] == 'SAN_PHAM'): ?>
                    <div class="sp-container">
                        <div class="fg-title">
                            <div class="fg-title-text">
                                <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                            </div>
                            <div class="fg-title-line">
                                <div></div>
                            </div>
                        </div>
                        <div class="sp-sidebar">
                            <div class="sp-sidebar-1">
                                <div class="sp-title-1">
                                    <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                                </div>
                                <div class="sp-title-re-1">
                                </div>
                                <div class="sp-list">
                                    <?php foreach($value['subPost'] as $index => $subValue):?>
                                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                            <div class="sp-list-item">
                                                <?php if($index == 8): ?>
                                                    Sản phẩm khác
                                                <?php elseif($index < 8): ?>
                                                    <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                                <?php endif;?>                                            
                                            </div>
                                        </a>
                                    <?php endforeach;?>
                                </div>
                            </div>
                        </div>
                        <div class="sp-content">
                            <?php foreach($value['subPost'] as $index => $subValue):?>
                                <div class="sp-content-1">
                                    <div class="sp-thumbnail-1">
                                        <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                    </div>
                                </div>
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                <?php endif;?>
            
                <?php if(isset($value['is_filter_page']) && $value['is_filter_page'] && $value['category'] == 'SAN_PHAM_MOI'): ?>
                    <div class="spmoi-container">
                        <div class="fg-title">
                            <div class="fg-title-text">
                                <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                            </div>
                        </div>
                        <div class="spmoi-content">
                            <?php foreach($value['subPost'] as $index => $subValue):?>
                                <div class="spmoi-content-1">
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                        <div class="spmoi-thumbnail-1">
                                            <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                        </div>
                                    </a>
                                    <div class="clearfix"></div>
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                        <div class="spmoi-title-1">
                                            <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                        </div>
                                    </a>
                                </div>
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                <?php endif;?>
            
                <?php if(isset($value['is_filter_page']) && $value['is_filter_page'] && $value['category'] == 'TIN_TUC'): ?>
                    <div class="tintuc-container">
                        <div class="fg-title">
                            <div class="fg-title-text">
                                <?php echo Utils_StringUtils::getTextFromPost($value, 'title')?>
                            </div>
                        </div>
                        <div class="tintuc-content">
                            <?php foreach($value['subPost'] as $index => $subValue):?>
                                <div class="tintuc-content-1">
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                        <div class="tintuc-thumbnail-1">
                                            <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                        </div>
                                    </a>
                                    <div class="tintuc-date-1">
                                        <?php echo $subValue['created_date'];?>
                                    </div>
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                        <div class="tintuc-title-1">
                                            <?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?>
                                        </div>
                                    </a>
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue) ?>">
                                        <div class="tintuc-more-1">
                                            xem thêm &gt;&gt;
                                        </div>
                                    </a>
                                </div>
                                <div class="clearfix"></div>
                            <?php endforeach;?>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
            <div class="clearfix"></div>
        </div>
    <?php endif;?>


    <?php if($this->post['is_filter_page']): ?>
        <div class="filter-post">
            <?php foreach($this->posts as $value):?>
                <?php if($value['is_filter_page']): ?>
                    <div class="panel panel-primary mb-10 no-border">
                        <div class="panel-heading">
                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>" class="white-color">
                                <?php echo Utils_StringUtils::getTextFromPost($value, 'title');?>
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <?php foreach($value['subPost'] as $subValue):?>
                            <div class="col-sm-6 col-md-4">
                                <div class="item-content-wrapper">
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue);?>">
                                        <h5><strong><?php echo Utils_StringUtils::getTextFromPost($subValue, 'title');?></strong></h5>
                                    </a>
                                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($subValue);?>">
                                        <div class="thumbnail">
                                            <img src="<?php echo $subValue['thumbnail'];?>" class="img-responsive">
                                        </div>
                                    </a>
                                    <br>
                                    <p><?php echo Utils_StringUtils::subText($subValue['description'], 60);?></p>
                                    <strong class="old-price"><?php echo $value['old_price'];?></strong>
                                    <div class="clearfix"></div>
                                    <strong class="price"><?php echo $subValue['price'];?></strong>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                <?php else:?>
                    <div class="item-by-list-content-wrapper">
                        <div class="row">
                            <div class="col-sm-4">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                                    <div class="thumbnail">
                                        <img src="<?php echo $value['thumbnail'];?>" class="img-responsive">
                                    </div>
                                </a>
                            </div>
                            <div class="col-sm-8">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                                    <h4><strong><?php echo Utils_StringUtils::getTextFromPost($value, 'title');?></strong></h4>
                                </a>
                                <p><?php echo Utils_StringUtils::subText($value['description'], 120);?></p>
                                <strong class="old-price"><?php echo $value['old_price'];?></strong>
                                <div class="clearfix"></div>
                                <strong class="price"><?php echo $value['price'];?></strong>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml');?>
        </div>
    <?php endif;?>


    <?php if($this->post['has_like_share']): ?>
        <div class="like-share-post">
            <div class="fb-like" data-href="<?php echo $this->fullUrl; ?>" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
        </div>        
    <?php endif;?>


    <?php if($this->post['has_advertisment']): ?>
        <div class="advertisment-post">
            <?php echo $this->layout()->configurations[POST_ADVERTISMENT_CONF]['value'] ?>        
        </div>
    <?php endif;?>


    <?php if($this->post['has_similar_post']): ?>
        <div class="similar-post">
            <div class="panel panel-primary mb-10 no-border">
                <div class="panel-heading">
                    Những sản phẩm tương tự
                </div>
            </div>
            <div class="row">
                <?php foreach($this->similarPosts as $value):?>
                    <div class="col-sm-6 col-md-4">
                        <div class="item-content-wrapper">
                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                                <h5><strong><?php echo Utils_StringUtils::getTextFromPost($value, 'title');?></strong></h5>
                            </a>
                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                                <div class="thumbnail">
                                    <img src="<?php echo $value['thumbnail'];?>" class="img-responsive">
                                </div>
                            </a>
                            <br>
                            <p><?php echo Utils_StringUtils::subText($value['description'], 60);?></p>
                            <strong class="old-price"><?php echo $value['old_price'];?></strong>
                            <div class="clearfix"></div>
                            <strong class="price"><?php echo $value['price'];?></strong>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    <?php endif;?>


    <?php if($this->post['has_comment']): ?>
        <div class="comment">
            <div class="fb-comments" data-href="<?php echo $this->fullUrl; ?>" data-width="100%" data-num-posts="10"></div>
        </div>
    <?php endif;?>


    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=412419298912724&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</div>