<style>
    .title-post-container {
        position: relative;
    }
    
    .title-post-wrapper {
        display: table;
        width: 150px;
        text-align: center;
        height: 150px;
        border-style: solid;
        border-width: 10px;
        border-color: #7bbb91;
        background-color: #438142;
        border-radius: 100px;
        position: absolute;
        font-size: 32px;
        color: white;
        bottom: 75px;
        left: 510px;
    }
    
    .title-post {
        display: table-cell;
        vertical-align: middle;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {
        .title-post-wrapper {
            left: 410px;
        }
    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .title-post-wrapper {
            bottom: 45px;
            left: 325px;
            width: 100px;
            height: 100px;
            font-size: 24px;
        }
    }
    
    @media (max-width: 767px) {
        .title-post-wrapper {
            width: 100px;
            height: 100px;
            font-size: 24px;
            position: static;
            margin: auto;
        }
    }
</style>
<div class="title-post-container">
    <div class="title-post-wrapper">
        <div class="title-post">
            <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title'); ?>
        </div>
    </div>
</div>