<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Configuration <small>Edit configuration</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Configuration
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<div class="configuration-form">
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('value_FOOTER_INFO_CONF')
            
            CKEDITOR.replace('value_PLUGIN_FOR_ALL_PAGE_CONF')
            
            CKEDITOR.replace('value_POST_ADVERTISMENT_CONF')            
        });
    </script>
    <?php if($this->errorMessage != ""): ?>
    <p class="error">
        <?php echo $this->errorMessage; ?>
    </p>
    <?php endif; ?>
     <?php echo $this->configurationForm; ?>
</div>