<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['CATEGORY'])): ?>
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                List of Post Category
                <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] > 1): ?>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail')) ?>" class="btn btn-primary pull-right">
                        <i class="fa fa-plus"></i> Add Category
                    </a>
                <?php endif;?>
            </h1>        
        </div>
    </div>
    <!-- /.row -->

    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Display name
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->category as $key => $value):?>
                <tr>
                    <td>
                        <?php echo $value['name'];?>
                    </td>
                    <td>
                        <?php echo $value['displayName'];?>
                    </td>
                    <td class="text-right">
                        <?php if($this->layout()->admin_role['CATEGORY'] == 1): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="View">
                                <i class="fa fa-eye"></i>
                            </a>
                        <?php endif;?>

                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] > 1): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'link_id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Add Child">
                                <i class="fa fa-plus"></i>
                            </a>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Edit">
                                <i class="fa fa-pencil"></i>
                            </a>
                        <?php endif;?>
                        
                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] > 2): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'delete', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                                <i class="fa fa-times"></i>
                            </a>
                        <?php endif;?>
                    </td>
                </tr>
                <?php foreach($value['subCategory'] as $value1):?>
                    <tr>
                        <td>
                            -------<?php echo $value1['name'];?>
                        </td>
                        <td>
                            <?php echo $value1['displayName'];?>
                        </td>
                        <td class="text-right">
                            <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] == 1): ?>
                                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value1['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="View">
                                    <i class="fa fa-eye"></i>
                                </a>
                            <?php endif;?>

                            <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] > 1): ?>
                                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'detail', 'id' => $value1['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Edit">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            <?php endif;?>

                            <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['CATEGORY'] > 2): ?>
                                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'category', 'action'=> 'delete', 'id' => $value1['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                                    <i class="fa fa-times"></i>
                                </a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endforeach;?>
        </tbody>
    </table>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>