<style>
    .breadcrumb-post-super-container {
        position: relative;
    }
    
    .breadcrumb-post-container {
        position: absolute;
        bottom: 75px;
        width: 100%;
    }
    
    .breadcrumb-post-wrapper {
        display: table;
        width: 150px;
        text-align: center;
        height: 150px;
        border-style: solid;
        border-width: 10px;
        border-color: #7bbb91;
        background-color: #438142;
        border-radius: 100px;
        font-size: 24px;
        color: white;
        margin: auto;
        text-transform: uppercase;
    }
    
    .breadcrumb-post {
        display: table-cell;
        vertical-align: middle;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {

    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .breadcrumb-post-container {
            bottom: 35px;
        }
        .breadcrumb-post-wrapper {
            width: 125px;
            height: 125px;
            font-size: 20px;
            margin-top: 15px;
        }
    }
    
    @media (max-width: 767px) {
        .breadcrumb-post-container {
            position: static;
        }
        .breadcrumb-post-wrapper {
            width: 125px;
            height: 125px;
            font-size: 20px;
            margin-top: 15px;
        }
    }
</style>
<?php if($this->post['has_breadcrumb']): ?>    
    <div class="breadcrumb-post-super-container">
        <div class="breadcrumb-post-container">
            <div class="breadcrumb-post-wrapper">
                <div class="breadcrumb-post">
                    <?php if(count($this->breadcrumb) > 1):?>
                        <?php echo Utils_StringUtils::getTextFromPost($this->breadcrumb[count($this->breadcrumb) - 2], 'title'); ?>
                    <?php else:?>
                        <?php echo Utils_StringUtils::getTextFromPost($this->breadcrumb[count($this->breadcrumb) - 1], 'title'); ?>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>