<style>
    .post-container {
        margin-top: 20px;
        position: relative;
    }
    
    .post-content {
        float: left;
        width: 440px;      
        font-size: 18px;        
        margin-right: 30px;
    }
    
    .post-map {
        width: 100%;
        margin-top: 20px;
    }
    
    .post-like-share {
        margin-top: 10px;
    }
    
    .contact-form {
        float: left;
        width: 700px;
        margin-top: 20px;
    }
    
    .contact-form input,
    .contact-form textarea {
        color: #ffffff;
        width: 100%;
        margin-bottom: 10px;
    }
    
    .contact-form button {
        background-color: #1c87c5;
        color: #ffffff;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {
        .post-content {
            width: 370px;
        }
        .contact-form {
            width: 570px;
        }
    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .post-content {
            width: 360px;
        }
        .contact-form {
            width: 360px;
        }
    }
    
    @media (max-width: 767px) {
        .post-content {
            width: 100%;
        }
        .contact-form {
            width: 100%;
        }
    }
</style>
<?php echo $this->render('post/custom/contact-baner.phtml');?>
<div class="post-container">
    <script>
        function sendContact(){
            if($('#name').val() != '' && $('#email').val() != '' && $('#comment').val() != ''){
                $.ajax({
                    url: '/mail/send-contact',
                    data: $('#contact-form').serializeArray(),
                    method: 'POST',
                    success: function(){
                        alert('Cảm ơn bạn đã đóng góp ý kiến cho chúng tôi!');
                        window.location.href = '/';
                    }
                });        
            }else{
                alert('Vui lòng nhập đủ thông tin!');
            }
        }
    </script>
    
    <?php echo $this->post['content'] ?>
    
    <div class="contact-form">
        <form id="contact-form">
            <input id="name" name="name" type="text" class="form-control" placeholder="Họ và tên">
            <input id="email" name="email" type="text" class="form-control" placeholder="Email">
            <input id="subject" name="subject" type="text" class="form-control" placeholder="Tiêu đề">
            <textarea id="comment" name="comment" class="form-control" rows="5" placeholder="Nội dung"></textarea>
            <button type="button" class="btn btn-default pull-right" onclick="sendContact()">Gửi</button>
        </form>
    </div>
    
    
</div>