<div>
    <?php if($this->post['is_filter_page']): ?>
        <div class="filter-post">
            <?php foreach($this->categories as $value):?>

                <?php $this->paramCategory = $value['category']; ?>
                <?php $this->paramPosts = $value['posts']; ?>

                <?php if($value['category']['name'] == 'SAN_PHAM_SUC_KHOE' || $value['category']['name'] == 'SAN_PHAM_NANG_LUONG' || $value['category']['name'] == 'SAN_PHAM_SAC_DEP'): ?>
                    <?php echo $this->render('post/custom/san-pham-full.phtml');?>
                <?php endif;?>
            
                <?php if($value['category']['name'] == 'SAN_PHAM_CATEGORY'): ?>
                    <?php echo $this->render('post/custom/san-pham-category.phtml');?>
                <?php endif;?>

                <?php if($value['category']['name'] == 'SAN_PHAM_BAN_CHAY'): ?>
                    <?php echo $this->render('post/custom/san-pham-ban-chay-short.phtml');?>
                <?php endif;?>

                <?php if($value['category']['name'] == 'VIDEO_NOI_BAT'): ?>
                    <?php echo $this->render('post/custom/video-noi-bat-short.phtml');?>
                <?php endif;?>

                <?php if($value['category']['name'] == 'SU_KIEN_NOI_BAT'): ?>
                    <?php echo $this->render('post/custom/su-kien-noi-bat-short.phtml');?>
                <?php endif;?>

                <?php if($value['category']['name'] == 'TIN_TUC'): ?>
                    <?php if (count($this->categories) > 1):?>
                        <?php echo $this->render('post/custom/tin-tuc-short.phtml');?>
                    <?php else:?>
                        <?php echo $this->render('post/custom/tin-tuc-full.phtml');?>
                    <?php endif;?>
                <?php endif;?>

            <?php endforeach;?>
        </div>
    <?php else:?>
        <?php if(strpos($this->post['category'], 'SAN_PHAM') != false): ?>
            <?php echo $this->render('post/custom/san-pham-detail.phtml');?>
        <?php elseif(strpos($this->post['category'], 'CONTACT') != false): ?>
            <?php echo $this->render('post/contact.phtml');?>
        <?php elseif(strpos($this->post['category'], 'TIN_TUC') != false): ?>
            <?php echo $this->render('post/custom/tin-tuc-detail.phtml');?>
        <?php elseif(strpos($this->post['category'], 'SU_KIEN') != false): ?>
            <?php echo $this->render('post/custom/su-kien-detail.phtml');?>
        <?php else: ?>
            <?php echo $this->render('post/content.phtml');?>
        <?php endif;?>
    <?php endif;?>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=412419298912724&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</div>