<style>
    .search-container {
        margin-top: 20px;
    }
    .search-container .keyword{
        color: #777;
        font-size: 24px;
        margin-bottom: 15px;
    }
    
    .search-container a{
        text-decoration: none;
    }
    
    .search-container .title{
        color: #777;
        font-size: 20px;
        margin-bottom: 10px;
    }
    
</style>
<div class="search-container">
    <div class="keyword">
        Tìm kiếm với từ khóa: "<?php echo $this->keyword; ?>"
    </div>
    <?php foreach($this->paginator as $value):?>
        <div class="item-by-list-content-wrapper">
            <div class="row">
                <div class="col-sm-4">
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                        <div class="thumbnail">
                            <img src="<?php echo $value['thumbnail']? $value['thumbnail'] : '/public/images/no_image.gif';?>" class="img-responsive">
                        </div>
                    </a>
                </div>
                <div class="col-sm-8">
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($value);?>">
                        <div class="title"><?php echo Utils_StringUtils::getTextFromPost($value, 'title');?></div>
                    </a>
                    <p><?php echo Utils_StringUtils::subText(Utils_StringUtils::getTextFromPost($value, 'description'), 120);?></p>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    <?php endforeach;?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml');?>
</div>
