<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['MENU'])): ?>
    
    <?php if($this->layout()->admin_role['MENU'] == 1): ?>
        <?php echo $this->render('form-disable.phtml');?>
    <?php endif;?>

    <form action="<?php echo $this->menuForm->getAction(); ?>" method="<?php echo $this->menuForm->getMethod(); ?>">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Add/Edit Menu Item
                    <div class="pull-right">
                        <?php echo $this->menuForm->getElement('submit'); ?>
                    </div>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="menu-form">
            <?php if($this->errorMessage != ""): ?>
            <p class="error">
                <?php echo $this->errorMessage; ?></p>
            <?php endif; ?>

            <?php echo $this->menuForm->getElement('id'); ?>
            <?php echo $this->menuForm->getElement('name'); ?>
            <?php echo $this->menuForm->getElement('link_id'); ?>
            <?php echo $this->menuForm->getElement('post_id'); ?>

        </div>
    </form>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>