<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['MENU'])): ?>

    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['MENU'] > 1): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'detail')) ?>">
                                    <i class="fa fa-plus"></i> Add Menu Item
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <div class="nestable-list" url="/admin/configuration/order" level="1">
                        <ol class="dd-list">
                            <?php foreach($this->menu as $index => $value):?>
                                <li class="dd-item" data-id="<?php echo $value['menu']['id'];?>">
                                    <div class="dd-handle">
                                        <?php echo $value['post']['title'];?>
                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['MENU'] > 2): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'delete', 'id' => $value['menu']['id'] )) ?>" need-confirm>
                                                <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                            </a>
                                        <?php endif;?>
                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['MENU'] > 1): ?>                        
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'detail', 'id' => $value['menu']['id'] )) ?>">
                                                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                            </a>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'detail', 'link_id' => $value['menu']['id'] )) ?>">
                                                <i class="fa fa-plus" data-toggle="tooltip" data-placement="top" title="Add Child"></i>
                                            </a>
                                        <?php endif;?>                    
                                    </div>
                                </li>
                                <ol class="dd-list">
                                    <?php foreach($value['submenu'] as $subvalue):?>
                                        <li class="dd-item" data-id="4">
                                            <div class="dd-handle">
                                                <?php echo $subvalue['post']['title'];?>
                                                <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['MENU'] > 2): ?>
                                                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'delete', 'id' => $subvalue['menu']['id'] )) ?>">
                                                        <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                                    </a>
                                                <?php endif;?>
                                                <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['MENU'] > 1): ?>
                                                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'menu', 'action'=> 'detail', 'id' => $subvalue['menu']['id'] )) ?>">
                                                        <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                                    </a>
                                                <?php endif;?>
                                            </div>
                                        </li>
                                    <?php endforeach;?>
                                </ol>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>