<a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'type'=> PAGE, 'language'=> 'vi')) ?>" class="btn btn-primary">
    <i class="fa fa-plus"></i> Add Post
</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Loại bài viết
            </th>
            <th>
                Hình thu nhỏ
            </th>
            <th>
                Tiêu đề
            </th>
            <th>
                Ngày tạo
            </th>
            <th>
                Người tạo
            </th>
            <th>
                Hành động
            </th>
        </tr>
    </thead>
    <tbody>
        <?php $oldvalue = null;?>
        <?php foreach($this->paginator as $key => $value):?>
        <tr>
            <td>
                <?php echo $value['display_name'];?>
            </td>
            <td>
                <img src="<?php echo $value['thumbnail'];?>" clas="img-responsive" style="max-width: 100px;"/>
            </td>
            <td>
                <?php echo $value['title'];?>
            </td>
            <td>
                <?php echo $value['created_date'];?>
            </td>
            <td>
                <?php echo $value['name'];?>
            </td>
            <td>
                <?php if($oldvalue):?>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'swap', 'post_id' => $value['id'], 'order_id' => $value['order_id'], 'above_post_id' => $oldvalue['id'], 'above_order_id' => $oldvalue['order_id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Up">
                        <i class="fa fa-arrow-up"></i>
                    </a>
                <?php endif;?>
                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Sửa">
                    <i class="fa fa-pencil"></i>
                </a>
                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'post', 'action'=> 'delete', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Xóa" need-confirm>
                    <i class="fa fa-times"></i>
                </a>
            </td>
            <?php $oldvalue = $value;?>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml');?>
<div class="clearfix"></div>