<?php if($this->paramPosts->getTotalItemCount() > 0):?>
    <style>
        .spcategory-container {
            margin-top: 20px;
        }

        .spcategory-container .title {
            color: #585a5c;
            font-size: 34px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .spcategory-container .content .item {
            float: left;
            margin-right: 30px;
            margin-top: 10px;
            width: 370px;
            position: relative;
        }

        .spcategory-container .content .item .thumbnail {
            border-width: 0px;
            overflow: hidden;
            margin-bottom: 0px;
            padding: 0px;
            border-radius: 0px;
            background-color: transparent;
        }

        .spcategory-container .content .item .title {
            color: #fff;
            padding: 15px 20px;
            position: absolute;
            bottom: 0px;
            left: 0px;
            font-size: 24px;
            font-weight: bold;
            background-color: #f69b0c;
            width: 100%;
            text-align: center;
        }

        .spcategory-container .content .item:nth-child(3n+3) {
            margin-right: 0px;
        }

        @media (min-width: 992px) and (max-width: 1199px) {
            .spcategory-container .content .item {
                width: 303px;
            }
        }

        @media (min-width: 768px) and (max-width: 991px) {
            .spcategory-container .title {
                font-size: 30px;
            }
            .spcategory-container .content .item {
                width: 236px;
                margin-right: 20px;
            }
            .spcategory-container .content .item .title {
                font-size: 20px;
            }
        }

        @media (max-width: 767px) {
            .spcategory-container {
                width: 100%;
                margin-top: 20px;
            }
            .spcategory-container .title {
                font-size: 18px;
            }
            .spcategory-container .content .item {
                margin-right: 5px;
                width: 100%;
            }
            .spcategory-container .content .item .title {
                font-size: 18px;
            }
        }
    </style>
    <?php echo $this->render('post/custom/san-pham-baner.phtml');?>
    <div class="spcategory-container">
        <div class="content">
            <?php foreach($this->paramPosts as $index => $post):?>
                <div class="item">
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                        <div class="thumbnail">
                            <img src="<?php echo $post['thumbnail'];?>" class="img-responsive">
                        </div>
                    </a>
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                        <div class="title">
                            <?php echo Utils_StringUtils::getTextFromPost($post, 'title');?>
                        </div>
                    </a>
                </div>
            <?php endforeach;?>
        </div>
        <div class="clearfix"></div>
    </div>
<?php endif;?>