<style>
    .post-container {
        margin-top: 20px;
    }
    
    .post-media {
        float: left;
        width: 570px;
        margin-right: 30px;
    }
    
    .post-title {
        font-size: 24px;
        color: #3c663d;
    }
    
    .post-like-share {
        margin-top: 10px;
    }
    
    .similar-post .fg-title-1 .fg-title-text {
        width: 290px;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {
        .post-media {
            width: 470px;
        }
        .similar-post .fg-title-1 .fg-title-text {
            width: 290px;
        }
    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .post-media {
            width: 360px;
        }
        .similar-post .fg-title-1 .fg-title-text {
            width: 240px;
        }
    }
    
    @media (max-width: 767px) {
        .post-media {
            width: 100%;
        }
        .similar-post .fg-title-1 .fg-title-text {
            width: 240px;
        }
    }
</style>
<div class="post-container">
    <div class="fg-title-2">
        <div class="fg-title-text">
            Chi tiết sản phẩm
        </div>
    </div>

    <?php if($this->post['has_media']): ?>
    <div id="preview-post" class="carousel post-media" data-ride="carousel">
        <div class="carousel-inner">
            <?php $ms=explode( ';', preg_replace( '/;+/', ';', trim($this->post['media'], ';'))); ?>
            <?php foreach($ms as $key=> $media):?>
            <div class="item <?php echo $key==0?'active':'' ?>">
                <img src="<?php echo $media ?>" class="center-block img-responsive">
            </div>
            <?php endforeach;?>
        </div>
        <a class="left carousel-control" href="#preview-post" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#preview-post" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <?php endif;?>

    <?php if($this->post['has_title']): ?>
    <div class="post-title">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title');?>
    </div>
    <?php endif;?>


    <?php if($this->post['has_description']): ?>
    <div class="post-description">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'description');?>
    </div>
    <?php endif;?>

    <div class="clearfix"></div>

    <?php if($this->post['has_like_share']): ?>
    <div class="post-like-share">
        <div class="fb-like" data-href="<?php echo $this->fullUrl; ?>" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
    </div>
    <?php endif;?>


    <?php if($this->post['has_content']): ?>
    <div class="post-content">
        <?php echo $this->post['content'] ?>
    </div>
    <?php endif;?>

    <?php if($this->post['has_advertisment']): ?>
    <div class="post-advertisment">
        <?php echo $this->layout()->configurations[POST_ADVERTISMENT_CONF]['value'] ?>
    </div>
    <?php endif;?>


    <?php if($this->post['has_similar_post']): ?>
    <div class="similar-post">

        <?php $this->paramCategory = array('display_name' => 'Sản phẩm khác'); ?>
        <?php $this->paramPosts = $this->similarPosts; ?>

        <?php echo $this->render('post/custom/san-pham-short.phtml');?>
    </div>
    <?php endif;?>


    <?php if($this->post['has_comment']): ?>
    <div class="comment">
        <div class="fb-comments" data-href="<?php echo $this->fullUrl; ?>" data-width="100%" data-num-posts="10"></div>
    </div>
    <?php endif;?>
</div>