<style>
    .spdetail-container {
        margin-top: 20px;
    }
    
    .spdetail-container .post-media {
        float: left;
        width: 490px;
        margin-right: 100px;
        margin-top: 20px;
    }
    
    .spdetail-container .post-title {
        color: #1c87c5;
        font-size: 34px;
        text-transform: uppercase;
        font-weight: bold;
    }
    
    .spdetail-container .post-like-share {
        margin-top: 10px;
    }
    
    .spdetail-container .post-description {
        margin-top: 20px;
    }
    
    .spdetail-container .post-content  {
        margin-top: 20px;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {
        .spdetail-container .post-media {
            width: 400px;
        }
    }
    
    @media (min-width: 768px) and (max-width: 991px) {
        .spdetail-container .post-media {
            width: 310px;
        }
    }
    
    @media (max-width: 767px) {
        .spdetail-container .post-media {
            width: 100%;
        }
    }
</style>
<?php echo $this->render('post/custom/san-pham-baner.phtml');?>
<div class="spdetail-container">
    <div class="post-title">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title');?>
    </div>

    <div id="preview-post" class="carousel post-media" data-ride="carousel">
        <div class="carousel-inner">
            <?php $ms=explode( ';', preg_replace( '/;+/', ';', trim($this->post['media'], ';'))); ?>
            <?php foreach($ms as $key=> $media):?>
            <div class="item <?php echo $key==0?'active':'' ?>">
                <img src="<?php echo $media ?>" class="center-block img-responsive">
            </div>
            <?php endforeach;?>
        </div>
        <a class="left carousel-control" href="#preview-post" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#preview-post" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>   

    <div class="post-description">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'description');?>
    </div>

    <div class="clearfix"></div>

    <?php if($this->post['has_like_share']): ?>
    <div class="post-like-share">
        <div class="fb-like" data-href="<?php echo $this->fullUrl; ?>" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
    </div>
    <?php endif;?>

    <div class="post-content">
        <?php echo $this->post['content'] ?>
    </div>

</div>