<style>
    .post-banner {
        width: 100%;
    }

    @media (min-width: 992px) and (max-width: 1199px) {
        .post-banner {
            margin-top: 20px;
        }
    }

    @media (min-width: 768px) and (max-width: 991px) {
        .post-banner {
            margin-top: 20px;
        }
    }

    @media (max-width: 767px) {
        .post-banner {
            margin-top: 20px;
        }
    }
</style>
<div class="post-banner">    
    <img src="/public/images/spbanner.png" class="img-responsive">
</div> 