<style>
    .sukien-container {
        margin-top: 20px;
    }
    
    .sukien-container .title {
        color: #1c87c5;
        font-size: 34px;
        text-transform: uppercase;
        font-weight: bold;
    }
    
    .sukien-container .content {
        margin-top: 10px;
    }
    
    @media (min-width: 992px) and (max-width: 1199px) {

    }
    
    @media (min-width: 768px) and (max-width: 991px) {

    }
    
    @media (max-width: 767px) {

    }
</style>
<?php echo $this->render('post/custom/tin-tuc-baner.phtml');?>
<div class="sukien-container">        
    <div class="title">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'title');?>
    </div>
    
    <div class="description">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'description');?>
    </div>

    <div class="content">
        <?php echo Utils_StringUtils::getTextFromPost($this->post, 'content');?>
    </div>

    <?php if($this->post['has_comment']): ?>
        <div class="comment">
            <div class="fb-comments" data-href="<?php echo $this->fullUrl; ?>" data-width="100%" data-num-posts="10"></div>
        </div>
    <?php endif;?>
</div>