<?php if($this->paramPosts->getTotalItemCount() > 0):?>
    <style>
        .tintuc-container {
            margin-top: 20px;
        }

        .tintuc-container .item-first {
            width: 470px;
            float: left;
            padding-right: 20px;
            border-right-style: solid;
            border-right-width: 1px;
            border-right-color: #717374;
        }

        .tintuc-container .item-first .thumbnail{
            margin-bottom: 10px;
            padding: 0px;
            border: none;
        }
        
        .tintuc-container .item-first .thumbnail img{
            height: 326px;
        }

        .tintuc-container .item-first .title {
            text-transform: uppercase;
            font-size: 18px;
            font-weight: bold;
            padding-bottom: 10px;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-bottom-color: #717374;
        }
        
        .tintuc-container .title a{
            color: #777;
            text-decoration: none;
        }
        
        .tintuc-container .title a:hover{
            color: #555;
        }

        .tintuc-container .item-first .description {
            padding-top: 10px;
            padding-bottom: 10px;
        }

        .tintuc-container .item {
            width: 680px;
            float: left;
            margin-left: 20px;
            padding-bottom: 10px;
            margin-bottom: 10px;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-bottom-color: #717374;
        }

        .tintuc-container .item .thumbnail {
            width: 170px;
            float: right;
            margin-bottom: 0px;
            padding: 0px;
            border: none;
        }
        
        .tintuc-container .item .thumbnail img{
            height: 170px;
        }

        .tintuc-container .item .title {
            font-size: 16px;
            font-weight: bold;
            padding-bottom: 10px;
        }
        
        .tintuc-container .item .description {
            padding-bottom: 10px;
        }
        
        .tintuc-container .date {
            float: left;
            padding: 18px 0px;
            border-radius: 36px;
            background-color: #ff6400;
            width: 55px;
            height: 55px;
            text-align: center;
            color: #ffffff;
            font-weight: bold;
        }
        
        .tintuc-container .more {
            float: right;
            padding: 5px 15px;
            color: #ffffff;
            font-style: italic;
            background: linear-gradient(#cfcbcb, #a4a4a5);
            margin-right: 15px;
            margin-top: 15px;
        }

        @media (min-width: 992px) and (max-width: 1199px) {
            .tintuc-container .item-first {
                width: 380px;            
            }
            .tintuc-container .item-first .thumbnail img{
                height: 300px;
            }
            .tintuc-container .item {
                width: 570px;
            }            
        }

        @media (min-width: 768px) and (max-width: 991px) {
            .tintuc-container .item-first {
                width: 270px;            
            }
            .tintuc-container .item-first .thumbnail img{
                height: 230px;
            }
            .tintuc-container .item {
                width: 460px;
            }
            .tintuc-container .item .thumbnail img{
                width: 120px;
            }
            .tintuc-container .item .thumbnail img{
                height: 120px;
            }
        }

        @media (max-width: 767px) {
            .tintuc-container .item-first {
                width: 100%;
                padding-right: 0px;
                border-right-color: transparent;
                padding-bottom: 10px;
                margin-bottom: 10px;
                border-bottom-style: solid;
                border-bottom-width: 1px;
                border-bottom-color: #717374;
            }
            .tintuc-container .item {
                width: 100%;
                margin-left: 0px;
            }
            .tintuc-container .item .thumbnail {
                width: 100%;
                float: none;
                margin-bottom: 10px;
            }
            .tintuc-container .item-first .title {
                text-transform: none;
                font-size: 16px;
                border-bottom-color: transparent;
            }
            .tintuc-container .item-first .description {
                padding-top: 0px;
            }
        }
    </style>
    <?php echo $this->render('post/custom/tin-tuc-baner.phtml');?>
    <div class="tintuc-container">
        <?php foreach($this->categories as $value):?>
            <div id="tintuc-content-<?php echo $value['category']['name']?>" class="pagination-container">
                <?php $this->paramPageSize = 4; ?>
                <?php $this->paramPosts = $value['posts']; ?>
                <?php foreach($value['posts'] as $index => $post):?>
                    <?php if($index % $this->paramPageSize == 0):?>
                        <div class="page-wrapper" page="<?php echo intval($index/$this->paramPageSize) + 1 ?>" >
                    <?php endif;?>
                    <?php if($index % $this->paramPageSize == 0):?>
                        <div class="item-first">
                            <div class="thumbnail">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                    <img src="<?php echo $post['thumbnail']?>" class="img-responsive">
                                </a>
                            </div>
                            <div class="title">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                    <?php echo $post['title']?>
                                </a>
                            </div>
                            <div class="description"><?php echo $post['description']?></div>
                            <div class="date"><?php echo date('d M', strtotime($post['created_date']))?></div>
                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                <div class="more">
                                    Xem tiếp
                                </div>
                            </a>
                        </div>
                    <?php else:?>
                        <div class="item">
                            <div class="thumbnail">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                    <img src="<?php echo $post['thumbnail']?>" class="img-responsive">
                                </a>
                            </div>
                            <div class="title">
                                <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                    <?php echo $post['title']?>
                                </a>
                            </div>
                            <div class="description"><?php echo $post['description']?></div>
                            <div class="date"><?php echo date('d M', strtotime($post['created_date']))?></div>
                            <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                                <div class="more">
                                    Xem tiếp
                                </div>
                            </a>
                        </div>
                    <?php endif;?>
                    <?php if($index % $this->paramPageSize == $this->paramPageSize - 1 || $index == $this->paramPosts->getTotalItemCount() - 1):?>
                        </div>
                    <?php endif;?>
                <?php endforeach;?>
                <div class="clearfix"></div>
                <?php echo $this->render('post/pagination.phtml');?>                
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>