<?php if($this->paramPosts->getTotalItemCount() > 0):?>
    <style>
        .tintuc-container {
            float: left;
            width: 870px;
            margin-top: 20px;
        }    
        
        .tintuc-container .item-first {
            position: relative;
            float: left;
            width: 510px;
        }
        
        .tintuc-container .item-first .thumbnail {
            border: none;
            position: relative;
            padding: 0px;
            border-radius: 0px;
            background-color: transparent;
            margin-bottom: 0px;
            width: 510px;
            height: 375px;
        }
        
        .tintuc-container .item-first .thumbnail img {
            width: 100%;
            height: 100%;
        }
        
        .tintuc-container .item-first .title-wrapper {
            position: absolute;
            left: 10px;
            bottom: 0px;
            background-color: rgba(251, 161, 2, 0.7);
            padding: 10px;
            color: #ffffff;
            width: 330px;
        }
        
        .tintuc-container .item-first .title {
            color: #ffffff;
            font-weight: bold;
            font-size: 16px;
            text-transform: uppercase;
        }
        
        .tintuc-container .item-first .more {
            float: right;
        }
        
        .tintuc-container .item {
            float: right;
            width: 340px;
            margin-bottom: 15px;
        }
        
        .tintuc-container .item .thumbnail {
            border: none;
            float: left;
            width: 160px;
            height: 115px;
            margin-bottom: 0px;
            padding: 0px;
            border-radius: 0px;
            background-color: transparent;
            margin-right: 10px;
        }
        
        .tintuc-container .item .thumbnail img {
            width: 100%;
            height: 100%;
        }

        .tintuc-container .item .date {
            color: #fba102;
            font-size: 14px;
        }

        .tintuc-container .item .title {
            font-size: 14px;
            color: #153242;
        }

        .tintuc-container .item .more {
            text-align: right;
            color: #51524c;
        }
        
        .tintuc-container .item:nth-child(3n+4) {
            margin-bottom: 0px;
        }
        
        .facebook-container {
            float: left;
            width: 300px;
        }

        @media (min-width: 992px) and (max-width: 1199px) {
            .tintuc-container {
                width: 720px;
            }
            .tintuc-container .item-first {
                width: 420px;
            }
            .tintuc-container .item-first .thumbnail {
                width: 420px;
                height: 340px;
            }
            .tintuc-container .item {
                width: 285px;
            }
            .tintuc-container .item .thumbnail {
                width: 130px;
                height: 103px;
            }
            .facebook-container {                
                width: 250px;
            }
        }

        @media (min-width: 768px) and (max-width: 991px) {
            .tintuc-container {
                width: 560px;
            }
            .tintuc-container .item-first {
                width: 330px;
            }
            .tintuc-container .item-first .thumbnail {
                width: 330px;
                height: 280px;
            }
            .tintuc-container .item-first .title-wrapper {
                width: 300px;
            }
            .tintuc-container .item {
                width: 220px;
            }
            .tintuc-container .item .thumbnail {
                width: 95px;
                height: 83px;
            }
            .tintuc-container .item .title {
                font-size: 12px;
            }
            .tintuc-container .item .date {
                font-size: 12px;
            }
            .facebook-container {                
                width: 190px;
            }
        }

        @media (max-width: 767px) {
            .tintuc-container {
                width: 100%;
            }
            .tintuc-container .item-first {
                width: 100%;
                margin-bottom: 15px;
            }
            .tintuc-container .item-first .thumbnail {
                width: 100%;
                height: auto;
            }
            .tintuc-container .item-first .title-wrapper {
                width: 90%;
            }
            .tintuc-container .item {
                width: 100%;
            }
            .tintuc-container .item .thumbnail {
                width: 95px;
                height: 83px;
            }
            .facebook-container {                
                width: 100%;
            }
        }
    </style>
    <div class="tintuc-container">
        <?php foreach($this->paramPosts as $index => $post):?>
            <?php if($index == 0):?>
                <div class="item-first">
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                        <div class="thumbnail">
                            <img src="<?php echo $post['thumbnail'];?>" class="img-responsive">
                        </div>
                    </a>
                    <div class="title-wrapper">
                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                            <div class="title">
                                <?php echo Utils_StringUtils::getTextFromPost($post, 'title');?>
                            </div>
                        </a>
                        <div class="description">
                            <?php echo Utils_StringUtils::getTextFromPost($post, 'description');?>
                        </div>
                        <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                            <div class="more">
                                <img src="/public/images/more.png">
                            </div>
                        </a>
                    </div>
                </div>
            <?php elseif($index < 4):?>
                <div class="item">
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                        <div class="thumbnail">
                            <img src="<?php echo $post['thumbnail'];?>" class="img-responsive">
                        </div>
                    </a>                    
                    <a href="<?php echo Utils_StringUtils::getUrlFromPost($post) ?>">
                        <div class="title">
                            <?php echo Utils_StringUtils::getTextFromPost($post, 'title');?>
                        </div>
                    </a>
                    <div class="date">
                        <?php echo $post[ 'created_date'];?>
                    </div>
                </div>
            <?php endif;?>
        <?php endforeach;?>
    </div>
    <div class="facebook-container">
        <div id="fb-root">&nbsp;</div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=412419298912724&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <div class="fb-like-box" data-colorscheme="light" data-header="false" data-href="https://www.facebook.com/CNIVn?fref=ts&__mref=message_bubble" data-show-border="false" data-show-faces="true" data-stream="false">&nbsp;</div>
    </div>
<?php endif;?>