<?php if($this->paramPosts->getTotalItemCount() > 0):?>
    <style>
        .video-container {
            margin-top: 20px;
        }

        .video-container .item-first {
            width: 780px;
            float: left;
            padding-right: 20px;
            border-right-style: solid;
            border-right-width: 1px;
            border-right-color: #717374;
        }

        .video-container .item-first .video iframe{
            margin-bottom: 10px;
            width: 100%;
            height: 490px;
        }

        .video-container .item-first .title {
            text-transform: uppercase;
            font-size: 18px;
            font-weight: bold;
            padding-bottom: 10px;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-bottom-color: #717374;
        }
        
        .video-container .title a{
            color: #777;
            text-decoration: none;
        }
        
        .video-container .title a:hover{
            color: #555;
        }

        .video-container .item-first .description {
            padding-top: 10px;
            padding-bottom: 10px;
        }

        .video-container .item {
            width: 370px;
            float: left;
            margin-left: 20px;
            padding-bottom: 10px;
            margin-bottom: 10px;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-bottom-color: #717374;
        }

        .video-container .item .thumbnail {
            width: 210px;
            float: left;
            margin-bottom: 0px;
            padding: 0px;
            border: none;
            margin-right: 10px;
        }
        
        .video-container .item .thumbnail img{
            height: 150px;
        }

        .video-container .item .title {
            font-size: 16px;
            font-weight: bold;
            padding-bottom: 10px;
        }
        
        .video-container .item .description {
            padding-bottom: 10px;
        }
        
        .ajpa .pagination > li > a, .ajpa .pagination > li > span {
            background-color: #1c87c5;
            border-color: transparent;
            padding: 0px;
            margin-left: 10px;
            color: #ffffff;
            border-radius: 25px;
            width: 25px;
            height: 25px;
            line-height: 25px;
            text-align: center;
        }
        
        .ajpa .pagination > li > a.active, .ajpa .pagination > li > span.active {
            background-color: #fe9d04;
        }

        @media (min-width: 992px) and (max-width: 1199px) {
            .video-container .item-first {
                width: 620px;            
            }
            .video-container .item-first .video iframe{
                height: 390px;
            }
            .video-container .item {
                width: 330px;
            }
            .video-container .item .thumbnail img{
                height: 125px;
            }
        }

        @media (min-width: 768px) and (max-width: 991px) {
            .video-container .item-first {
                width: 480px;            
            }
            .video-container .item-first .video iframe{
                height: 315px;
            }
            .video-container .item {
                width: 250px;
            }
            .video-container .item .thumbnail{
                width: 130px;
            }
            .video-container .item .thumbnail img{
                height: 100px;
            }
        }

        @media (max-width: 767px) {
            .video-container .item-first {
                width: 100%;
                padding-right: 0px;
                border-right-color: transparent;
                padding-bottom: 10px;
                margin-bottom: 10px;
                border-bottom-style: solid;
                border-bottom-width: 1px;
                border-bottom-color: #717374;
            }
            .video-container .item {
                width: 100%;
                margin-left: 0px;
            }
            .video-container .item .thumbnail {
                width: 100%;
                float: none;
                margin-bottom: 10px;
            }
            .video-container .item .thumbnail img{
                height: auto;
            }
            .video-container .item-first .title {
                text-transform: none;
                font-size: 16px;
                border-bottom-color: transparent;
            }
            .video-container .item-first .description {
                padding-top: 0px;
            }
        }
    </style>
    <?php echo $this->render('post/custom/video-baner.phtml');?>
    <script>
        $(document).ready(function(){
            
            
            $.ajax({
                url: 'https://www.googleapis.com/youtube/v3/search?',
                data: {
                    key: 'AIzaSyC_0nsshxWoyK8SHpElUphhNseEe657EN0',
                    channelId: 'UCli4FciTjCjf_0_g5p0DzQA',
                    part: 'snippet,id',
                    order: 'date',
                    maxResults: 50
                },
                method: 'GET',
                dataType: 'json',
                success: function(data){
                    var page = 1;
                    var pageSize = 3;
                    var html = '';
                    $.each(data.items, function(k, v){
                        if(k % pageSize == 0){
                        
                            html += '<div class="page-wrapper" page="' + page + '" >';                                            
                            html +=     '<div class="item-first">';
                            html +=         '<div class="video">';
                            html +=             '<iframe src="https://www.youtube.com/embed/' + v.id.videoId + '" frameborder="0" allowfullscreen></iframe>';
                            html +=         '</div>';
                            html +=         '<div class="title">';
                            html +=             v.snippet.title;
                            html +=         '</div>';
                            html +=         '<div class="description">';
                            html +=             v.snippet.description;
                            html +=         '</div>';
                            html +=     '</div>';
                        
                        }
                        
                            html +=     '<div class="item">';
                            html +=         '<div class="hidden content" >';
                            html +=             '<iframe src="https://www.youtube.com/embed/' + v.id.videoId + '" frameborder="0" allowfullscreen></iframe>';
                            html +=         '</div>';
                            html +=         '<div class="thumbnail">';
                            html +=             '<a href="#">';
                            html +=                 '<img src="' + v.snippet.thumbnails.medium.url + '" class="img-responsive">';
                            html +=             '</a>';
                            html +=         '</div>';
                            html +=         '<div class="title">';
                            html +=             '<a href="#">';
                            html +=                 v.snippet.title;
                            html +=             '</a>';
                            html +=         '</div>';
                            /*html +=         '<div class="description">';
                            html +=             v.snippet.description;
                            html +=         '</div>';*/
                            html +=     '</div>';
                        
                        if(k % pageSize == 2 || k == data.items.length - 1){
                            html += '</div>';
                            page ++;
                        }                        
                    });
                    
                        html += '<nav class="ajpa">'
                        html +=     '<ul class="pagination pull-right">'
                        
                    for(var i = 0; i < page - 1; i++){
                        html +=         '<li>'
                        html +=             '<a href="javascript:void(0)" page="' + (i + 1) + '">' + (i + 1) + '</a>'
                        html +=         '</li>'
                    }
                    
                        html +=     '</ul>'
                        html += '</nav>'
                    
                    $('#video-content').html(html);
                    
                    $('.video-container .item a').click(function(){
                        $('.video-container .item-first .video').html($(this).parents('.item').find('.content').html());
                        $('.video-container .item-first .title').html($(this).parents('.item').find('.title').html());
                        $('.video-container .item-first .description').html($(this).parents('.item').find('.description').html());
                        return false;
                    });
                    
                    $('.pagination-container a[page]').click(function(){
                        $('.pagination-container a[page]').removeClass('active');
                        $(this).addClass('active');
                        $(this).parents('.pagination-container').find('.page-wrapper').hide();  
                        $(this).parents('.pagination-container').find('.page-wrapper[page=' + $(this).attr('page') + ']').show();
                    });
                    $('.pagination-container a[page=1]').click();
                }
            });            
        })
    </script>
    <div class="video-container">
        <?php foreach($this->categories as $value):?>
            <div id="video-content" class="pagination-container">
                
                                
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>