<?php if($this->paramPosts->getTotalItemCount() > 0):?>
    <style>
        .videonoibat-container {
            margin-top: 20px;
            width: 750px;
            float: left;
        }

        .videonoibat-container .title {
            color: #ffffff;
            font-size: 28px;
            text-transform: uppercase;
            background-color: #1c87c5;
            padding: 10px 15px;
        }

        .videonoibat-container .content .item {
            position: relative;
            cursor: pointer;
        }

        .videonoibat-container .content .item .thumbnail {
            overflow: hidden;
            margin-bottom: 0px;
            padding: 0px;
            border-radius: 0px;
            background-color: transparent;
            border: none;
        }

        .videonoibat-container .content .item .thumbnail img {
            width: 100%;
            height: 430px;
        }

        .videonoibat-container .content .item .title {
            color: #fff;
            padding: 5px 20px;
            position: absolute;
            bottom: 20px;
            width: 640px;
            font-size: 18px;
            background-color: #1c87c5;
        }
        
        .videonoibat-container .content .item .cover {
            position: absolute;
            top: 0px;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.0);
            color: rgba(255, 255, 255, 0.0);
            padding: 25px;
            text-align: center;
            -webkit-transition: background .5s ease-out, color .5s ease-out;
            -moz-transition: background .5s ease-out, color .5s ease-out;
            -o-transition: background .5s ease-out, color .5s ease-out;
            transition: background .5s ease-out, color .5s ease-out;
        }
        
        .videonoibat-container .content .item .cover img{
            margin-top: 100px;
        }
        
        .videonoibat-container .content .item:hover .cover {
            background-color: rgba(0, 0, 0, 0.8);
            color: rgba(255, 255, 255, 1.0);
        }
        
        .videonoibat-container .content .item iframe {
            width: 100%;
            height: 375px;
        }
        
        .videonoibat-container .content .item button.close {
            margin-right: -11px;
            margin-top: -17px;
            color: red;
            font-size: 36px;
        }

        @media (min-width: 992px) and (max-width: 1199px) {
            .videonoibat-container {
                width: 620px;
            }
            .videonoibat-container .content .item .thumbnail img {
                height: 350px;
            }
            .videonoibat-container .content .item .title {
                width: 500px;
                font-size: 16px;
            }
        }

        @media (min-width: 768px) and (max-width: 991px) {
            .videonoibat-container {
                width: 480px;
            }
            .videonoibat-container .title {
                font-size: 24px;
            }
            .videonoibat-container .content .item .thumbnail img {
                height: 275px;
            }
            .videonoibat-container .content .item .title {
                width: 400px;
                font-size: 14px;
            }
        }

        @media (max-width: 767px) {
            .videonoibat-container {
                width: 100%;
            }
            .videonoibat-container .title {
                font-size: 18px;
            }
            .videonoibat-container .content .item .thumbnail img {
                height: auto;
            }
            .videonoibat-container .content .item .title {
                width: 90%;
                font-size: 14px;
            }
        }
    </style>
    <div class="videonoibat-container">
        <div class="title">
            <?php echo Utils_StringUtils::getTextFromPost($this->paramCategory, 'display_name')?>
        </div>
        <div class="content">
            <?php foreach($this->paramPosts as $index => $post):?>
                <?php if($index == 0):?>
                    <div class="item">
                        <div class="thumbnail">
                            <img src="<?php echo $post['thumbnail'];?>" class="img-responsive">
                        </div>
                        <div class="cover" data-toggle="modal" data-target="#video_<?php echo $post['id']?>">
                            <img src="/public/images/play-icon.png">
                        </div>
                        <div class="title">
                            <?php echo Utils_StringUtils::getTextFromPost($post, 'title');?>
                        </div>
                        <div class="modal fade" id="video_<?php echo $post['id']?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <div class="modal-body">
                                        <?php echo Utils_StringUtils::getTextFromPost($post, 'content');?>
                                    </div>              
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            <?php endforeach;?>
        </div>
        <div class="clearfix"></div>        
    </div>
<?php endif;?>