<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Add/Edit User
        </h1>
    </div>
</div>
<!-- /.row -->

<div class="menu-form">
    <?php if($this->errorMessage != ""): ?>
    <p class="error">
        <?php echo $this->errorMessage; ?></p>
    <?php endif; ?>

    <form action="<?php echo $this->userForm->getAction(); ?>" method="<?php echo $this->userForm->getMethod(); ?>">            
        <?php echo $this->userForm->getElement('id'); ?>
        <?php echo $this->userForm->getElement('name'); ?>
        <?php echo $this->userForm->getElement('username'); ?>
        <?php echo $this->userForm->getElement('password'); ?>        
        <?php echo $this->userForm->getElement('role'); ?>        

        <?php echo $this->userForm->getElement('submit'); ?>
    </form>
</div>