<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['USER'])): ?>
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                List of User
                <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 1): ?>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail')) ?>" class="btn btn-primary pull-right">
                        <i class="fa fa-plus"></i> Add User
                    </a>
                <?php endif;?>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>
                    Display Name
                </th>
                <th>
                    Username
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->user as $key => $value):?>
                <tr>
                    <td>
                        <?php echo $value['name'];?>
                    </td>
                    <td>
                        <?php echo $value['username'];?>
                    </td>
                    <td class="text-right">
                        <?php if($this->layout()->admin_role['USER'] == 1): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="View">
                                <i class="fa fa-eye"></i>
                            </a>
                        <?php endif;?>
                        
                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 1): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Edit">
                                <i class="fa fa-pencil"></i>
                            </a>
                        <?php endif;?>
                        
                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 2): ?>
                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'delete', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                                <i class="fa fa-times"></i>
                            </a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>