<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            List of User
        </h1>
    </div>
</div>
<!-- /.row -->

<a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail')) ?>" class="btn btn-primary">
    <i class="fa fa-plus"></i> Add User
</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Display Name
            </th>
            <th>
                Username
            </th>
            <th>
                Hành động
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->user as $key => $value):?>
            <tr>
                <td>
                    <?php echo $value['name'];?>
                </td>
                <td>
                    <?php echo $value['username'];?>
                </td>
                <td>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Edit">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'delete', 'id' => $value['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                        <i class="fa fa-times"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<div class="clearfix"></div>