<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['MENU'])): ?>
    
    <form action="<?php echo $this->menuForm->getAction(); ?>" method="<?php echo $this->menuForm->getMethod(); ?>">
        <?php if($this->layout()->admin_role['MENU'] == 1): ?>
            <?php echo $this->render('form-disable.phtml');?>
        <?php endif;?>
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <header>
                        <div class="icons">
                            <i class="fa fa-pencil"></i>
                        </div>
                        <h5></h5>
                        <div class="toolbar">
                            <div class="btn-group">
                                <?php echo $this->menuForm->getElement('submit'); ?>
                            </div>
                        </div>
                    </header>
                    <div class="body">
                        <div class="menu-form">
                            <?php if($this->errorMessage != ""): ?>
                            <p class="error">
                                <?php echo $this->errorMessage; ?></p>
                            <?php endif; ?>

                            <?php echo $this->menuForm->getElement('id'); ?>
                            <?php echo $this->menuForm->getElement('name'); ?>                            
                            <?php echo $this->menuForm->getElement('link_id'); ?>
                            <?php echo $this->menuForm->getElement('value'); ?>
                            <?php echo $this->menuForm->getElement('post_id'); ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>