<?php if ($this->pageCount > 1): ?>
<nav>
    <ul class="pagination pull-right">
        <li class="<?php echo isset($this->previous)?'':'disabled' ?>">
            <a href="<?php echo '?page=' . $this->previous; ?>">
                <span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span>
            </a>
        </li>
        
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page == $this->current): ?>
                <li class="active">
                    <a href="#"><?php echo $page; ?> <span class="sr-only">(current)</span></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?php echo '?page=' . $page; ?>"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <li class="<?php echo isset($this->next)?'':'disabled' ?>">
            <a href="<?php echo '?page=' . $this->next; ?>">
                <span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>
<?php endif; ?>
<?php if ($this->totalItemCount == 0): ?>
Không có sản phẩm nào
<?php endif; ?>