<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Media <small>List of media</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Media
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<script>
	$(document).ready(function(){
		$('input:file').change(function(){
			$(this).parents("form").submit();
		});
	});
</script>
<div>
	<form enctype="multipart/form-data" action="/admin/media/upload" method="POST" >
		<input name="file" type="file" style="float: right;"  multiple=""/>
	</form>
</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Hình thu nhỏ
            </th>
            <th>
                Url
            </th>
            <th>
                Hành động
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->files as $value):?>
        <tr>
            <td>
                <img src="<?php echo MEDIA_PATH . $value;?>" clas="img-responsive" style="max-width: 100px;"/>
            </td>
            <td>
                <?php echo MEDIA_PATH . $value;?>
            </td>
            <td>
                <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'media', 'action'=> 'delete', 'file' => $value )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<div class="clearfix"></div>