<a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'detail')) ?>" class="btn btn-primary">
    <i class="fa fa-plus"></i> Add Slide Item
</a>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Tiêu đề
            </th>
            <th>
                Hình
            </th>
            <th>
                Ngày tạo
            </th>
            <th>
                Người tạo
            </th>
            <th>
                Hành động
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->slide as $key => $value):?>
            <tr>
                <td>
                    <?php echo $value['post']['title'];?>
                </td>
                <td>
                    <img src="<?php echo $value['slide']['value'];?>" clas="img-responsive" style="max-width: 100px;"/>
                </td>
                <td>
                    <?php echo $value['post']['created_date'];?>
                </td>
                <td>
                    <?php echo $value['post']['name'];?>
                </td>
                <td>
                    <?php if($key>0):?>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'swap', 'post_id' => $value['post']['id'], 'order_id' => $value['post']['order_id'], 'above_post_id' => $this->slide[$key-1]['post']['id'], 'above_order_id' => $this->slide[$key-1]['post']['order_id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Up">
                        <i class="fa fa-arrow-up"></i>
                    </a>
                    <?php endif;?>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'detail', 'id' => $value['slide']['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Edit">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'delete', 'id' => $value['slide']['id'] )) ?>" data-toggle="tooltip" data-placement="top" title="Delete" need-confirm>
                        <i class="fa fa-times"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<div class="clearfix"></div>