
<div class="login">
    <div class="form-signin">
        <div class="text-center">
            <h4>Bappro Admin Panel</h4>
        </div>
        <hr>
        <div class="tab-content">
            <div id="login" class="tab-pane active">
                <form id="popup-validation" enctype="multipart/form-data" action="<?php echo $this->loginForm->getAction(); ?>" method="<?php echo $this->loginForm->getMethod(); ?>">
                    <?php if($this->errorMessage != ""): ?>                    
                        <div class="alert alert-danger" role="alert">
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            <span class="sr-only">Error:</span>
                            <?php echo $this->errorMessage; ?>
                        </div>
                    <?php endif; ?>
                    <p class="text-muted text-center">
                        Enter your username and password
                    </p>                    
                    <input name="username" type="text" placeholder="Username" class="form-control top">
                    <input name="password" type="password" placeholder="Password" class="form-control bottom">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                </form>
            </div>
            <div id="forgot" class="tab-pane">
                <form action="index.html">
                    <p class="text-muted text-center">Enter your valid e-mail</p>
                        <input type="email" placeholder="mail@domain.com" class="form-control">
                    <br>
                    <button class="btn btn-lg btn-danger btn-block" type="submit">Recover Password</button>
                </form>
            </div>
        </div>
        <hr>
        <div class="text-center">
            <ul class="list-inline">
                <li> <a class="text-muted" href="#login" data-toggle="tab">Login</a>  </li>
                <li> <a class="text-muted" href="#forgot" data-toggle="tab">Forgot Password</a>  </li>
            </ul>
        </div>
    </div>
</div>