<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['USER'])): ?>

    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 1): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail')) ?>">
                                    <i class="fa fa-plus"></i> Add User
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <table class="table table-bordered table-condensed table-hover table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Display Name
                                </th>
                                <th>
                                    Username
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->user as $key => $value):?>
                                <tr>
                                    <td>
                                        <?php echo $value['name'];?>
                                    </td>
                                    <td>
                                        <?php echo $value['username'];?>
                                    </td>
                                    <td class="text-right">
                                        <?php if($this->layout()->admin_role['USER'] == 1): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail', 'id' => $value['id'] )) ?>">
                                                <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="View"></i>
                                            </a>
                                        <?php endif;?>

                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 1): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'detail', 'id' => $value['id'] )) ?>">
                                                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                            </a>
                                        <?php endif;?>

                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['USER'] > 2): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'user', 'action'=> 'delete', 'id' => $value['id'] )) ?>" need-confirm>
                                                <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                            </a>
                                        <?php endif;?>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>