
<script>
$(document).ready(function() {
	setTimeout(function(){
		window.location.href = "<?php echo $this->url(array ('controller'=> 'trang-chu', 'action'=> 'index' )) ?>"
	}, 5000);
});
</script>
<!--<div class="text" style="text-align: center;font-size: 14px;">
Cám ơn bạn đã đóng góp ý kiến cho Maximark chúng tôi. Sau vài giây sẽ tự động chuyển về trang chủ.<br/>
</div>-->
<div class="text" style="text-align: center;font-size: 14px;">
Sau vài giây sẽ tự động chuyển về trang chủ.<br/>
</div>
<div class="text" style="text-align: center;">
	<img class="minh-hoa" src="/public/images/thanks.png" style="width: 765px;">
</div>
<div class="clearfix"></div>