<div class="text" style="float:left;width: 300px;">

Công Ty Cổ Phần Đầu Tư AN PHONG<br/>Số 3 đường Ba Tháng Hai, Q.10, TP.HCM<br/>
Email:<a href='mailto:anphong@maximark.com.vn'style="color: blue;"> anphong@maximark.com.vn </a> <br/>
Tel: (84.8) 38342002 – 38356617<br/>
Fax: (84.8) 38342001<br/>
</div>
<div class="map" style="float:right;width: 450px;">
	<img class="minh-hoa" width="100%" src="/public/images/map-2.jpg">
	<img class="minh-hoa" width="100%" height="258px" src="/public/images/gioi-thieu-img-14.jpg">
</div>
<div id="form-wrapper" style="float:left;width: 300px;">
	<?php echo $this->yKienForm; ?>
</div>
<div class="clearfix"></div>
<div class="he-thong-sieu-thi">
	<div id="he-thong-sieu-thi-wrapper">
		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_32.jpg">
			</div>
			<strong>Trung Tâm Thương Mại MAXIMARK Ba tháng Hai</strong><br/>
			Số 3-3C đường 3/2, Quận 10, Tp.HCM<br/>
			<strong>TEL :</strong> 08 3 8325 324 - 08 3 835 66 17<br/>
			<strong>FAX :</strong> 08 3  8391 285<br/>
			<strong>Email :</strong> <a href="mailto:maximark.3-2@maximark.com.vn">maximark.3-2@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/maps.php">Sơ đồ mặt bằng</a>  | <a href="http://www.maximark.com.vn/view.php?img=images/map/3-2.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi</a>
		</div>

		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_conghoa.jpg">
			</div>
			<strong>Trung Tâm Thương Mại MAXIMARK Cộng Hòa </strong><br/>
			Số 15-17 Cộng Hòa, Q. Tân Bình, Tp.HCM<br/>
			<strong>TEL :</strong> 08 3 811 75 70 <br/>
			<strong>FAX :</strong> 08 3 811 75 74 <br/>
			<strong>Email :</strong> <a href="mailto:maximark.ch@maximark.com.vn">maximark.ch@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/maps.php?mx=2">Sơ đồ mặt bằng </a>  | <a href="http://www.maximark.com.vn/view.php?img=images/map/conghoa.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi </a>
		</div>

		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_cantho.jpg">
			</div>
			<strong>Siêu Thị MAXIMARK Cần Thơ</strong><br/>
			2 Hùng Vương – CMT8, P. Thới Bình, Q.Ninh Kiều, Tp. Cần Thơ<br/>
			<strong>TEL :</strong> 0710 376 6933 <br/>
			<strong>FAX :</strong> 0710 376 6934 <br/>
			<strong>Email :</strong> <a href="mailto:maximark.ct@maximark.com.vn">maximark.ct@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/maps.php?mx=3">Sơ đồ mặt bằng </a>  | <a href="http://www.maximark.com.vn/view.php?img=images/map/cantho.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi </a>
		</div>

		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_nhathidau.jpg">
			</div>
			<strong>Sân khấu MAXIMARK Cộng Hòa</strong><br/>
			Số 15-17 Cộng Hòa, Q. Tân Bình, Tp.HCM<br/>
			<strong>TEL :</strong> 08 3 811 75 70 <br/>
			<strong>FAX :</strong> 08 3 811 75 74 <br/>
			<strong>Email :</strong> <a href="mailto:maximark.ch@maximark.com.vn">maximark.ch@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/index.php?act=adv&id=37">Hình ảnh hoạt động </a>| <a href="http://www.maximark.com.vn/view.php?img=images/map/conghoa.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi </a>
		</div>

		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_nhatrang02.jpg">
			</div>
			<strong>Trung Tâm Thương Mại MAXIMARK Nha Trang</strong><br/>
			Số 60 Thái Nguyên, Tp. Nha Trang<br/>
			<strong>TEL :</strong> 058 3 818 727  <br/>
			<strong>FAX :</strong> 058 3 818 757 <br/>
			<strong>Email :</strong> <a href="mailto:maximark.nt@maximark.com.vn">maximark.nt@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/maps.php?mx=4">Sơ đồ mặt bằng</a>  | <a href="http://www.maximark.com.vn/view.php?img=images/map/60nhatrang.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi </a>
		</div>

		<div class="text info">
			<div style="float:left;">
				<img src="/public/images/mx_CAMRANH.jpg">
			</div>
			<strong>Siêu Thị MAXIMARK Cam Ranh</strong><br/>
			Số 3 Hùng Vương, Tp. Cam Ranh<br/>
			<strong>TEL :</strong> 058 3 953 388  <br/>
			<strong>FAX :</strong> 058 3 956 288 <br/>
			<strong>Email :</strong> <a href="mailto:maximark.cr@maximark.com.vn">maximark.cr@maximark.com.vn</a><br/>
			<strong>Website :</strong> http://maximark.com.vn<br/>
			<a href="http://www.maximark.com.vn/index.php?act=hethong#">Sơ đồ mặt bằng</a>  | <a href="http://www.maximark.com.vn/view.php?img=images/map/89hungvuong_camranh.jpg" width="743px" height="443px" rel="external">Bản đồ đường đi </a>
		</div>
	</div>
</div>