<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SLIDE:READONLY']) || isset($this->layout()->admin_role['SLIDE:ADD']) || isset($this->layout()->admin_role['SLIDE:EDIT']) || isset($this->layout()->admin_role['SLIDE:DELETE'])): ?>
    <form enctype="multipart/form-data" action="<?php echo $this->slideForm->getAction(); ?>" method="<?php echo $this->slideForm->getMethod(); ?>">
        <?php if(isset($this->layout()->admin_role['SLIDE:READONLY'])): ?>
            <?php echo $this->render('form-disable.phtml');?>
        <?php endif;?>
        <div class="row">
            <div class="col-lg-12">
                <div class="box">
                    <header>
                        <div class="icons">
                            <i class="fa fa-pencil"></i>
                        </div>
                        <h5></h5>
                        <div class="toolbar">
                            <div class="btn-group">
                                <?php echo $this->slideForm->getElement('submit'); ?>
                            </div>
                        </div>
                    </header>
                    <div class="body">
                        <div class="slide-form">
                            <?php if($this->errorMessage != ""): ?>
                            <p class="error">
                                <?php echo $this->errorMessage; ?></p>
                            <?php endif; ?>

                            <?php echo $this->slideForm->getElement('id'); ?>
                            <?php echo $this->slideForm->getElement('name'); ?>
                            <?php echo $this->slideForm->getElement('value'); ?>
                            <?php echo $this->slideForm->getElement('file'); ?>
                            <img class="img-responsive" src="<?php echo $this->slideForm->getElement('value')->getValue(); ?>">
                            <?php echo $this->slideForm->getElement('post_id'); ?>       
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>