<?php if($this->layout()->admin_issuper || isset($this->layout()->admin_role['SLIDE'])): ?>
    
    <div class="row">
        <div class="col-lg-12">
            <div class="box">
                <header>
                    <div class="icons">
                        <i class="fa fa-table"></i>
                    </div>
                    <h5></h5>
                    <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['SLIDE'] > 1): ?>
                        <div class="toolbar">
                            <div class="btn-group">
                                <a class="btn btn-primary btn-sm" href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'detail')) ?>">
                                    <i class="fa fa-plus"></i> Add Slide Item
                                </a>
                            </div>
                        </div>
                    <?php endif;?>
                </header>
                <div class="body">
                    <div class="nestable-list" url="/admin/configuration/order" level="1">
                        <ol class="dd-list">
                            <?php foreach($this->slide as $key => $value):?>
                                <li class="dd-item" data-id="<?php echo $value['slide']['id'];?>">
                                    <div class="dd-handle">
                                        <div class="col-sm-3">
                                            <img src="<?php echo $value['slide']['value'];?>" class="img-responsive"/>
                                        </div>
                                        <div class="col-sm-3">
                                            <?php echo $value['post']['title'];?>
                                        </div>
                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['SLIDE'] > 2): ?>
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'delete', 'id' => $value['slide']['id'] )) ?>" need-confirm>
                                                <i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                                            </a>
                                        <?php endif;?>
                                        <?php if($this->layout()->admin_issuper || $this->layout()->admin_role['SLIDE'] > 1): ?>                        
                                            <a href="<?php echo $this->url(array ('module'=> 'admin', 'controller'=> 'slide', 'action'=> 'detail', 'id' => $value['slide']['id'] )) ?>">
                                                <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                                            </a>
                                        <?php endif;?>
                                        <div class="clearfix"></div>
                                    </div>
                                </li>
                            <?php endforeach;?>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
<?php else:?>
    <?php echo $this->render('permission-denied.phtml');?>
<?php endif;?>